
/*
	File generated by NetTiers templates [www.nettiers.net]
	Important: Do not modify this file. Edit the file BankAccounts.cs instead.
*/

#region using directives
using System;
using System.ComponentModel;
using System.Collections;
using System.Xml.Serialization;
using System.Runtime.Serialization;

using EmployeeDB.BLL.Validation;
#endregion

namespace EmployeeDB.BLL
{
	///<summary>
	/// An object representation of the 'BankAccounts' table. [No description found the database]	
	///</summary>
	[Serializable]
	[DataObject, CLSCompliant(true)]
	public abstract partial class BankAccountsBase : EntityBase, IBankAccounts, IEntityId<BankAccountsKey>, System.IComparable, System.ICloneable, ICloneableEx, IEditableObject, IComponent, INotifyPropertyChanged
	{		
		#region Variable Declarations
		
		/// <summary>
		///  Hold the inner data of the entity.
		/// </summary>
		private BankAccountsEntityData entityData;
		
		/// <summary>
		/// 	Hold the original data of the entity, as loaded from the repository.
		/// </summary>
		private BankAccountsEntityData _originalData;
		
		/// <summary>
		/// 	Hold a backup of the inner data of the entity.
		/// </summary>
		private BankAccountsEntityData backupData; 
		
		/// <summary>
		/// 	Key used if Tracking is Enabled for the <see cref="EntityLocator" />.
		/// </summary>
		private string entityTrackingKey;
		
		/// <summary>
		/// 	Hold the parent TList&lt;entity&gt; in which this entity maybe contained.
		/// </summary>
		/// <remark>Mostly used for databinding</remark>
		[NonSerialized]
		private TList<BankAccounts> parentCollection;
		
		private bool inTxn = false;
		
		/// <summary>
		/// Occurs when a value is being changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event BankAccountsEventHandler ColumnChanging;		
		
		/// <summary>
		/// Occurs after a value has been changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event BankAccountsEventHandler ColumnChanged;
		
		#endregion Variable Declarations
		
		#region Constructors
		///<summary>
		/// Creates a new <see cref="BankAccountsBase"/> instance.
		///</summary>
		public BankAccountsBase()
		{
			this.entityData = new BankAccountsEntityData();
			this.backupData = null;
		}		
		
		///<summary>
		/// Creates a new <see cref="BankAccountsBase"/> instance.
		///</summary>
		///<param name="_employeeId"></param>
		///<param name="_bankName"></param>
		///<param name="_accountNumber"></param>
		///<param name="_createdOn"></param>
		public BankAccountsBase(System.Int32 _employeeId, System.String _bankName, System.String _accountNumber, 
			System.DateTime? _createdOn)
		{
			this.entityData = new BankAccountsEntityData();
			this.backupData = null;

			this.EmployeeId = _employeeId;
			this.BankName = _bankName;
			this.AccountNumber = _accountNumber;
			this.CreatedOn = _createdOn;
		}
		
		///<summary>
		/// A simple factory method to create a new <see cref="BankAccounts"/> instance.
		///</summary>
		///<param name="_employeeId"></param>
		///<param name="_bankName"></param>
		///<param name="_accountNumber"></param>
		///<param name="_createdOn"></param>
		public static BankAccounts CreateBankAccounts(System.Int32 _employeeId, System.String _bankName, System.String _accountNumber, 
			System.DateTime? _createdOn)
		{
			BankAccounts newBankAccounts = new BankAccounts();
			newBankAccounts.EmployeeId = _employeeId;
			newBankAccounts.BankName = _bankName;
			newBankAccounts.AccountNumber = _accountNumber;
			newBankAccounts.CreatedOn = _createdOn;
			return newBankAccounts;
		}
				
		#endregion Constructors
			
		#region Properties	
		
		#region Data Properties		
		/// <summary>
		/// 	Gets or sets the BankAccountId property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		
		




		[ReadOnlyAttribute(false)/*, XmlIgnoreAttribute()*/, DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(true, true, false)]
		public virtual System.Int32 BankAccountId
		{
			get
			{
				return this.entityData.BankAccountId; 
			}
			
			set
			{
				if (this.entityData.BankAccountId == value)
					return;
				
                OnPropertyChanging("BankAccountId");                    
				OnColumnChanging(BankAccountsColumn.BankAccountId, this.entityData.BankAccountId);
				this.entityData.BankAccountId = value;
				this.EntityId.BankAccountId = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(BankAccountsColumn.BankAccountId, this.entityData.BankAccountId);
				OnPropertyChanged("BankAccountId");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the EmployeeId property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false)]
		public virtual System.Int32 EmployeeId
		{
			get
			{
				return this.entityData.EmployeeId; 
			}
			
			set
			{
				if (this.entityData.EmployeeId == value)
					return;
				
                OnPropertyChanging("EmployeeId");                    
				OnColumnChanging(BankAccountsColumn.EmployeeId, this.entityData.EmployeeId);
				this.entityData.EmployeeId = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(BankAccountsColumn.EmployeeId, this.entityData.EmployeeId);
				OnPropertyChanged("EmployeeId");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the BankName property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 50)]
		public virtual System.String BankName
		{
			get
			{
				return this.entityData.BankName; 
			}
			
			set
			{
				if (this.entityData.BankName == value)
					return;
				
                OnPropertyChanging("BankName");                    
				OnColumnChanging(BankAccountsColumn.BankName, this.entityData.BankName);
				this.entityData.BankName = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(BankAccountsColumn.BankName, this.entityData.BankName);
				OnPropertyChanged("BankName");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the AccountNumber property. 
		///		
		/// </summary>
		/// <value>This type is varchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 50)]
		public virtual System.String AccountNumber
		{
			get
			{
				return this.entityData.AccountNumber; 
			}
			
			set
			{
				if (this.entityData.AccountNumber == value)
					return;
				
                OnPropertyChanging("AccountNumber");                    
				OnColumnChanging(BankAccountsColumn.AccountNumber, this.entityData.AccountNumber);
				this.entityData.AccountNumber = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(BankAccountsColumn.AccountNumber, this.entityData.AccountNumber);
				OnPropertyChanged("AccountNumber");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the CreatedOn property. 
		///		
		/// </summary>
		/// <value>This type is datetime.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null it is up to the developer to check using the HasValue property
		/// and perform business logic appropriately.
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.DateTime? CreatedOn
		{
			get
			{
				return this.entityData.CreatedOn; 
			}
			
			set
			{
				if (this.entityData.CreatedOn == value)
					return;
				
                OnPropertyChanging("CreatedOn");                    
				OnColumnChanging(BankAccountsColumn.CreatedOn, this.entityData.CreatedOn);
				this.entityData.CreatedOn = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(BankAccountsColumn.CreatedOn, this.entityData.CreatedOn);
				OnPropertyChanged("CreatedOn");
			}
		}
		
		#endregion Data Properties		

		#region Source Foreign Key Property
				
		/// <summary>
		/// Gets or sets the source <see cref="Employee"/>.
		/// </summary>
		/// <value>The source Employee for EmployeeId.</value>
        [XmlIgnore()]
		[Browsable(false), System.ComponentModel.Bindable(System.ComponentModel.BindableSupport.Yes)]
		public virtual Employee EmployeeIdSource
      	{
            get { return entityData.EmployeeIdSource; }
            set { entityData.EmployeeIdSource = value; }
      	}
		#endregion
		
		#region Children Collections
		#endregion Children Collections
		
		#endregion
		#region Validation
		
		/// <summary>
		/// Assigns validation rules to this object based on model definition.
		/// </summary>
		/// <remarks>This method overrides the base class to add schema related validation.</remarks>
		protected override void AddValidationRules()
		{
			//Validation rules based on database schema.
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("BankName", "Bank Name", 50));
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("AccountNumber", "Account Number", 50));
		}
   		#endregion
		
		#region Table Meta Data
		/// <summary>
		///		The name of the underlying database table.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string TableName
		{
			get { return "BankAccounts"; }
		}
		
		/// <summary>
		///		The name of the underlying database table's columns.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string[] TableColumns
		{
			get
			{
				return new string[] {"BankAccountId", "EmployeeId", "BankName", "AccountNumber", "CreatedOn"};
			}
		}
		#endregion 
		
		#region IEditableObject
		
		#region  CancelAddNew Event
		/// <summary>
        /// The delegate for the CancelAddNew event.
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
		public delegate void CancelAddNewEventHandler(object sender, EventArgs e);
    
    	/// <summary>
		/// The CancelAddNew event.
		/// </summary>
		[field:NonSerialized]
		public event CancelAddNewEventHandler CancelAddNew ;

		/// <summary>
        /// Called when [cancel add new].
        /// </summary>
        public void OnCancelAddNew()
        {    
			if (!SuppressEntityEvents)
			{
	            CancelAddNewEventHandler handler = CancelAddNew ;
            	if (handler != null)
	            {    
    	            handler(this, EventArgs.Empty) ;
        	    }
	        }
        }
		#endregion 
		
		/// <summary>
		/// Begins an edit on an object.
		/// </summary>
		void IEditableObject.BeginEdit() 
	    {
	        //Console.WriteLine("Start BeginEdit");
	        if (!inTxn) 
	        {
	            this.backupData = this.entityData.Clone() as BankAccountsEntityData;
	            inTxn = true;
	            //Console.WriteLine("BeginEdit");
	        }
	        //Console.WriteLine("End BeginEdit");
	    }
	
		/// <summary>
		/// Discards changes since the last <c>BeginEdit</c> call.
		/// </summary>
	    void IEditableObject.CancelEdit() 
	    {
	        //Console.WriteLine("Start CancelEdit");
	        if (this.inTxn) 
	        {
	            this.entityData = this.backupData;
	            this.backupData = null;
				this.inTxn = false;

				if (this.bindingIsNew)
	        	//if (this.EntityState == EntityState.Added)
	        	{
					if (this.parentCollection != null)
						this.parentCollection.Remove( (BankAccounts) this ) ;
				}	            
	        }
	        //Console.WriteLine("End CancelEdit");
	    }
	
		/// <summary>
		/// Pushes changes since the last <c>BeginEdit</c> or <c>IBindingList.AddNew</c> call into the underlying object.
		/// </summary>
	    void IEditableObject.EndEdit() 
	    {
	        //Console.WriteLine("Start EndEdit" + this.custData.id + this.custData.lastName);
	        if (this.inTxn) 
	        {
	            this.backupData = null;
				if (this.IsDirty) 
				{
					if (this.bindingIsNew) {
						this.EntityState = EntityState.Added;
						this.bindingIsNew = false ;
					}
					else
						if (this.EntityState == EntityState.Unchanged) 
							this.EntityState = EntityState.Changed ;
				}

				this.bindingIsNew = false ;
	            this.inTxn = false;	            
	        }
	        //Console.WriteLine("End EndEdit");
	    }
	    
	    /// <summary>
        /// Gets or sets the parent collection of this current entity, if available.
        /// </summary>
        /// <value>The parent collection.</value>
	    [XmlIgnore]
		[Browsable(false)]
	    public override object ParentCollection
	    {
	        get 
	        {
	            return this.parentCollection;
	        }
	        set 
	        {
	            this.parentCollection = value as TList<BankAccounts>;
	        }
	    }
	    
	    /// <summary>
        /// Called when the entity is changed.
        /// </summary>
	    private void OnEntityChanged() 
	    {
	        if (!SuppressEntityEvents && !inTxn && this.parentCollection != null) 
	        {
	            this.parentCollection.EntityChanged(this as BankAccounts);
	        }
	    }


		#endregion
		
		#region ICloneable Members
		///<summary>
		///  Returns a Typed BankAccounts Entity 
		///</summary>
		protected virtual BankAccounts Copy(IDictionary existingCopies)
		{
			if (existingCopies == null)
			{
				// This is the root of the tree to be copied!
				existingCopies = new Hashtable();
			}

			//shallow copy entity
			BankAccounts copy = new BankAccounts();
			existingCopies.Add(this, copy);
			copy.SuppressEntityEvents = true;
				copy.BankAccountId = this.BankAccountId;
				copy.EmployeeId = this.EmployeeId;
				copy.BankName = this.BankName;
				copy.AccountNumber = this.AccountNumber;
				copy.CreatedOn = this.CreatedOn;
			
			if (this.EmployeeIdSource != null && existingCopies.Contains(this.EmployeeIdSource))
				copy.EmployeeIdSource = existingCopies[this.EmployeeIdSource] as Employee;
			else
				copy.EmployeeIdSource = MakeCopyOf(this.EmployeeIdSource, existingCopies) as Employee;
		
			copy.EntityState = this.EntityState;
			copy.SuppressEntityEvents = false;
			return copy;
		}		
		
		
		
		///<summary>
		///  Returns a Typed BankAccounts Entity 
		///</summary>
		public virtual BankAccounts Copy()
		{
			return this.Copy(null);	
		}
		
		///<summary>
		/// ICloneable.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone()
		{
			return this.Copy(null);
		}
		
		///<summary>
		/// ICloneableEx.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone(IDictionary existingCopies)
		{
			return this.Copy(existingCopies);
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x)
		{
			if (x == null)
				return null;
				
			if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable Interface.");
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x, IDictionary existingCopies)
		{
			if (x == null)
				return null;
			
			if (x is ICloneableEx)
			{
				// Return a deep copy of the object
				return ((ICloneableEx)x).Clone(existingCopies);
			}
			else if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable or IClonableEx Interface.");
		}
		
		
		///<summary>
		///  Returns a Typed BankAccounts Entity which is a deep copy of the current entity.
		///</summary>
		public virtual BankAccounts DeepCopy()
		{
			return EntityHelper.Clone<BankAccounts>(this as BankAccounts);	
		}
		#endregion
		
		#region Methods	
			
		///<summary>
		/// Revert all changes and restore original values.
		///</summary>
		public override void CancelChanges()
		{
			IEditableObject obj = (IEditableObject) this;
			obj.CancelEdit();

			this.entityData = null;
			if (this._originalData != null)
			{
				this.entityData = this._originalData.Clone() as BankAccountsEntityData;
			}
			else
			{
				//Since this had no _originalData, then just reset the entityData with a new one.  entityData cannot be null.
				this.entityData = new BankAccountsEntityData();
			}
		}	
		
		/// <summary>
		/// Accepts the changes made to this object.
		/// </summary>
		/// <remarks>
		/// After calling this method, properties: IsDirty, IsNew are false. IsDeleted flag remains unchanged as it is handled by the parent List.
		/// </remarks>
		public override void AcceptChanges()
		{
			base.AcceptChanges();

			// we keep of the original version of the data
			this._originalData = null;
			this._originalData = this.entityData.Clone() as BankAccountsEntityData;
		}
		
		#region Comparision with original data
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="column">The column.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool IsPropertyChanged(BankAccountsColumn column)
		{
			switch(column)
			{
					case BankAccountsColumn.BankAccountId:
					return entityData.BankAccountId != _originalData.BankAccountId;
					case BankAccountsColumn.EmployeeId:
					return entityData.EmployeeId != _originalData.EmployeeId;
					case BankAccountsColumn.BankName:
					return entityData.BankName != _originalData.BankName;
					case BankAccountsColumn.AccountNumber:
					return entityData.AccountNumber != _originalData.AccountNumber;
					case BankAccountsColumn.CreatedOn:
					return entityData.CreatedOn != _originalData.CreatedOn;
			
				default:
					return false;
			}
		}
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="columnName">The column name.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public override bool IsPropertyChanged(string columnName)
		{
			return 	IsPropertyChanged(EntityHelper.GetEnumValue< BankAccountsColumn >(columnName));
		}
		
		/// <summary>
		/// Determines whether the data has changed from original.
		/// </summary>
		/// <returns>
		/// 	<c>true</c> if data has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool HasDataChanged()
		{
			bool result = false;
			result = result || entityData.BankAccountId != _originalData.BankAccountId;
			result = result || entityData.EmployeeId != _originalData.EmployeeId;
			result = result || entityData.BankName != _originalData.BankName;
			result = result || entityData.AccountNumber != _originalData.AccountNumber;
			result = result || entityData.CreatedOn != _originalData.CreatedOn;
			return result;
		}	
		
		///<summary>
		///  Returns a BankAccounts Entity with the original data.
		///</summary>
		public BankAccounts GetOriginalEntity()
		{
			if (_originalData != null)
				return CreateBankAccounts(
				_originalData.EmployeeId,
				_originalData.BankName,
				_originalData.AccountNumber,
				_originalData.CreatedOn
				);
				
			return (BankAccounts)this.Clone();
		}
		#endregion
	
	#region Value Semantics Instance Equality
        ///<summary>
        /// Returns a value indicating whether this instance is equal to a specified object using value semantics.
        ///</summary>
        ///<param name="Object1">An object to compare to this instance.</param>
        ///<returns>true if Object1 is a <see cref="BankAccountsBase"/> and has the same value as this instance; otherwise, false.</returns>
        public override bool Equals(object Object1)
        {
			// Cast exception if Object1 is null or DbNull
			if (Object1 != null && Object1 != DBNull.Value && Object1 is BankAccountsBase)
				return ValueEquals(this, (BankAccountsBase)Object1);
			else
				return false;
        }

        /// <summary>
		/// Serves as a hash function for a particular type, suitable for use in hashing algorithms and data structures like a hash table.
        /// Provides a hash function that is appropriate for <see cref="BankAccountsBase"/> class 
        /// and that ensures a better distribution in the hash table
        /// </summary>
        /// <returns>number (hash code) that corresponds to the value of an object</returns>
        public override int GetHashCode()
        {
			return this.BankAccountId.GetHashCode() ^ 
					this.EmployeeId.GetHashCode() ^ 
					((this.BankName == null) ? string.Empty : this.BankName.ToString()).GetHashCode() ^ 
					((this.AccountNumber == null) ? string.Empty : this.AccountNumber.ToString()).GetHashCode() ^ 
					((this.CreatedOn == null) ? string.Empty : this.CreatedOn.ToString()).GetHashCode();
        }
		
		///<summary>
		/// Returns a value indicating whether this instance is equal to a specified object using value semantics.
		///</summary>
		///<param name="toObject">An object to compare to this instance.</param>
		///<returns>true if toObject is a <see cref="BankAccountsBase"/> and has the same value as this instance; otherwise, false.</returns>
		public virtual bool Equals(BankAccountsBase toObject)
		{
			if (toObject == null)
				return false;
			return ValueEquals(this, toObject);
		}
		#endregion
		
		///<summary>
		/// Determines whether the specified <see cref="BankAccountsBase"/> instances are considered equal using value semantics.
		///</summary>
		///<param name="Object1">The first <see cref="BankAccountsBase"/> to compare.</param>
		///<param name="Object2">The second <see cref="BankAccountsBase"/> to compare. </param>
		///<returns>true if Object1 is the same instance as Object2 or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
		public static bool ValueEquals(BankAccountsBase Object1, BankAccountsBase Object2)
		{
			// both are null
			if (Object1 == null && Object2 == null)
				return true;

			// one or the other is null, but not both
			if (Object1 == null ^ Object2 == null)
				return false;
				
			bool equal = true;
			if (Object1.BankAccountId != Object2.BankAccountId)
				equal = false;
			if (Object1.EmployeeId != Object2.EmployeeId)
				equal = false;
			if ( Object1.BankName != null && Object2.BankName != null )
			{
				if (Object1.BankName != Object2.BankName)
					equal = false;
			}
			else if (Object1.BankName == null ^ Object2.BankName == null )
			{
				equal = false;
			}
			if ( Object1.AccountNumber != null && Object2.AccountNumber != null )
			{
				if (Object1.AccountNumber != Object2.AccountNumber)
					equal = false;
			}
			else if (Object1.AccountNumber == null ^ Object2.AccountNumber == null )
			{
				equal = false;
			}
			if ( Object1.CreatedOn != null && Object2.CreatedOn != null )
			{
				if (Object1.CreatedOn != Object2.CreatedOn)
					equal = false;
			}
			else if (Object1.CreatedOn == null ^ Object2.CreatedOn == null )
			{
				equal = false;
			}
					
			return equal;
		}
		
		#endregion
		
		#region IComparable Members
		///<summary>
		/// Compares this instance to a specified object and returns an indication of their relative values.
		///<param name="obj">An object to compare to this instance, or a null reference (Nothing in Visual Basic).</param>
		///</summary>
		///<returns>A signed integer that indicates the relative order of this instance and obj.</returns>
		public virtual int CompareTo(object obj)
		{
			throw new NotImplementedException();
			//return this. GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]) .CompareTo(((BankAccountsBase)obj).GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]));
		}
		
		/*
		// static method to get a Comparer object
        public static BankAccountsComparer GetComparer()
        {
            return new BankAccountsComparer();
        }
        */

        // Comparer delegates back to BankAccounts
        // Employee uses the integer's default
        // CompareTo method
        /*
        public int CompareTo(Item rhs)
        {
            return this.Id.CompareTo(rhs.Id);
        }
        */

/*
        // Special implementation to be called by custom comparer
        public int CompareTo(BankAccounts rhs, BankAccountsColumn which)
        {
            switch (which)
            {
            	
            	
            	case BankAccountsColumn.BankAccountId:
            		return this.BankAccountId.CompareTo(rhs.BankAccountId);
            		
            		                 
            	
            	
            	case BankAccountsColumn.EmployeeId:
            		return this.EmployeeId.CompareTo(rhs.EmployeeId);
            		
            		                 
            	
            	
            	case BankAccountsColumn.BankName:
            		return this.BankName.CompareTo(rhs.BankName);
            		
            		                 
            	
            	
            	case BankAccountsColumn.AccountNumber:
            		return this.AccountNumber.CompareTo(rhs.AccountNumber);
            		
            		                 
            	
            	
            	case BankAccountsColumn.CreatedOn:
            		return this.CreatedOn.Value.CompareTo(rhs.CreatedOn.Value);
            		
            		                 
            }
            return 0;
        }
        */
	
		#endregion
		
		#region IComponent Members
		
		private ISite _site = null;

		/// <summary>
		/// Gets or Sets the site where this data is located.
		/// </summary>
		[XmlIgnore]
		[SoapIgnore]
		[Browsable(false)]
		public ISite Site
		{
			get{ return this._site; }
			set{ this._site = value; }
		}

		#endregion

		#region IDisposable Members
		
		/// <summary>
		/// Notify those that care when we dispose.
		/// </summary>
		[field:NonSerialized]
		public event System.EventHandler Disposed;

		/// <summary>
		/// Clean up. Nothing here though.
		/// </summary>
		public virtual void Dispose()
		{
			this.parentCollection = null;
			this.Dispose(true);
			GC.SuppressFinalize(this);
		}
		
		/// <summary>
		/// Clean up.
		/// </summary>
		protected virtual void Dispose(bool disposing)
		{
			if (disposing)
			{
				EventHandler handler = Disposed;
				if (handler != null)
					handler(this, EventArgs.Empty);
			}
		}
		
		#endregion
				
		#region IEntityKey<BankAccountsKey> Members
		
		// member variable for the EntityId property
		private BankAccountsKey _entityId;

		/// <summary>
		/// Gets or sets the EntityId property.
		/// </summary>
		[XmlIgnore]
		public virtual BankAccountsKey EntityId
		{
			get
			{
				if ( _entityId == null )
				{
					_entityId = new BankAccountsKey(this);
				}

				return _entityId;
			}
			set
			{
				if ( value != null )
				{
					value.Entity = this;
				}
				
				_entityId = value;
			}
		}
		
		#endregion
		
		#region EntityState
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false) , XmlIgnoreAttribute()]
		public override EntityState EntityState 
		{ 
			get{ return entityData.EntityState;	 } 
			set{ entityData.EntityState = value; } 
		}
		#endregion 
		
		#region EntityTrackingKey
		///<summary>
		/// Provides the tracking key for the <see cref="EntityLocator"/>
		///</summary>
		[XmlIgnore]
		public override string EntityTrackingKey
		{
			get
			{
				if(entityTrackingKey == null)
					entityTrackingKey = new System.Text.StringBuilder("BankAccounts")
					.Append("|").Append( this.BankAccountId.ToString()).ToString();
				return entityTrackingKey;
			}
			set
		    {
		        if (value != null)
                    entityTrackingKey = value;
		    }
		}
		#endregion 
		
		#region ToString Method
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return string.Format(System.Globalization.CultureInfo.InvariantCulture,
				"{6}{5}- BankAccountId: {0}{5}- EmployeeId: {1}{5}- BankName: {2}{5}- AccountNumber: {3}{5}- CreatedOn: {4}{5}{7}", 
				this.BankAccountId,
				this.EmployeeId,
				(this.BankName == null) ? string.Empty : this.BankName.ToString(),
				(this.AccountNumber == null) ? string.Empty : this.AccountNumber.ToString(),
				(this.CreatedOn == null) ? string.Empty : this.CreatedOn.ToString(),
				System.Environment.NewLine, 
				this.GetType(),
				this.Error.Length == 0 ? string.Empty : string.Format("- Error: {0}\n",this.Error));
		}
		
		#endregion ToString Method
		
		#region Inner data class
		
	/// <summary>
	///		The data structure representation of the 'BankAccounts' table.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	[EditorBrowsable(EditorBrowsableState.Never)]
	[Serializable]
	internal protected class BankAccountsEntityData : ICloneable, ICloneableEx
	{
		#region Variable Declarations
		private EntityState currentEntityState = EntityState.Added;
		
		#region Primary key(s)
		/// <summary>			
		/// BankAccountId : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "BankAccounts"</remarks>
		public System.Int32 BankAccountId;
			
		#endregion
		
		#region Non Primary key(s)
		
		/// <summary>
		/// EmployeeId : 
		/// </summary>
		public System.Int32 EmployeeId = (int)0;
		
		/// <summary>
		/// BankName : 
		/// </summary>
		public System.String BankName = null;
		
		/// <summary>
		/// AccountNumber : 
		/// </summary>
		public System.String AccountNumber = null;
		
		/// <summary>
		/// CreatedOn : 
		/// </summary>
		public System.DateTime? CreatedOn = null;
		#endregion
			
		#region Source Foreign Key Property
				
		private Employee _employeeIdSource = null;
		
		/// <summary>
		/// Gets or sets the source <see cref="Employee"/>.
		/// </summary>
		/// <value>The source Employee for EmployeeId.</value>
		[XmlIgnore()]
		[Browsable(false)]
		public virtual Employee EmployeeIdSource
      	{
            get { return this._employeeIdSource; }
            set { this._employeeIdSource = value; }
      	}
		#endregion
        
		#endregion Variable Declarations

		#region Data Properties

		#endregion Data Properties
		#region Clone Method

		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public Object Clone()
		{
			BankAccountsEntityData _tmp = new BankAccountsEntityData();
						
			_tmp.BankAccountId = this.BankAccountId;
			
			_tmp.EmployeeId = this.EmployeeId;
			_tmp.BankName = this.BankName;
			_tmp.AccountNumber = this.AccountNumber;
			_tmp.CreatedOn = this.CreatedOn;
			
			#region Source Parent Composite Entities
			if (this.EmployeeIdSource != null)
				_tmp.EmployeeIdSource = MakeCopyOf(this.EmployeeIdSource) as Employee;
			#endregion
		
			#region Child Collections
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public object Clone(IDictionary existingCopies)
		{
			if (existingCopies == null)
				existingCopies = new Hashtable();
				
			BankAccountsEntityData _tmp = new BankAccountsEntityData();
						
			_tmp.BankAccountId = this.BankAccountId;
			
			_tmp.EmployeeId = this.EmployeeId;
			_tmp.BankName = this.BankName;
			_tmp.AccountNumber = this.AccountNumber;
			_tmp.CreatedOn = this.CreatedOn;
			
			#region Source Parent Composite Entities
			if (this.EmployeeIdSource != null && existingCopies.Contains(this.EmployeeIdSource))
				_tmp.EmployeeIdSource = existingCopies[this.EmployeeIdSource] as Employee;
			else
				_tmp.EmployeeIdSource = MakeCopyOf(this.EmployeeIdSource, existingCopies) as Employee;
			#endregion
		
			#region Child Collections
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		#endregion Clone Method
		
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public EntityState	EntityState
		{
			get { return currentEntityState;  }
			set { currentEntityState = value; }
		}
	
	}//End struct

		#endregion
		
				
		
		#region Events trigger
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="BankAccountsColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanging(BankAccountsColumn column)
		{
			OnColumnChanging(column, null);
			return;
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="BankAccountsColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanged(BankAccountsColumn column)
		{
			OnColumnChanged(column, null);
			return;
		} 
		
		
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="BankAccountsColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanging(BankAccountsColumn column, object value)
		{
			if(IsEntityTracked && EntityState != EntityState.Added && !EntityManager.TrackChangedEntities)
                EntityManager.StopTracking(entityTrackingKey);
                
			if (!SuppressEntityEvents)
			{
				BankAccountsEventHandler handler = ColumnChanging;
				if(handler != null)
				{
					handler(this, new BankAccountsEventArgs(column, value));
				}
			}
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="BankAccountsColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanged(BankAccountsColumn column, object value)
		{
			if (!SuppressEntityEvents)
			{
				BankAccountsEventHandler handler = ColumnChanged;
				if(handler != null)
				{
					handler(this, new BankAccountsEventArgs(column, value));
				}
			
				// warn the parent list that i have changed
				OnEntityChanged();
			}
		} 
		#endregion
			
	} // End Class
	
	
	#region BankAccountsEventArgs class
	/// <summary>
	/// Provides data for the ColumnChanging and ColumnChanged events.
	/// </summary>
	/// <remarks>
	/// The ColumnChanging and ColumnChanged events occur when a change is made to the value 
	/// of a property of a <see cref="BankAccounts"/> object.
	/// </remarks>
	public class BankAccountsEventArgs : System.EventArgs
	{
		private BankAccountsColumn column;
		private object value;
		
		///<summary>
		/// Initalizes a new Instance of the BankAccountsEventArgs class.
		///</summary>
		public BankAccountsEventArgs(BankAccountsColumn column)
		{
			this.column = column;
		}
		
		///<summary>
		/// Initalizes a new Instance of the BankAccountsEventArgs class.
		///</summary>
		public BankAccountsEventArgs(BankAccountsColumn column, object value)
		{
			this.column = column;
			this.value = value;
		}
		
		///<summary>
		/// The BankAccountsColumn that was modified, which has raised the event.
		///</summary>
		///<value cref="BankAccountsColumn" />
		public BankAccountsColumn Column { get { return this.column; } }
		
		/// <summary>
        /// Gets the current value of the column.
        /// </summary>
        /// <value>The current value of the column.</value>
		public object Value{ get { return this.value; } }

	}
	#endregion
	
	///<summary>
	/// Define a delegate for all BankAccounts related events.
	///</summary>
	public delegate void BankAccountsEventHandler(object sender, BankAccountsEventArgs e);
	
	#region BankAccountsComparer
		
	/// <summary>
	///	Strongly Typed IComparer
	/// </summary>
	public class BankAccountsComparer : System.Collections.Generic.IComparer<BankAccounts>
	{
		BankAccountsColumn whichComparison;
		
		/// <summary>
        /// Initializes a new instance of the <see cref="T:BankAccountsComparer"/> class.
        /// </summary>
		public BankAccountsComparer()
        {            
        }               
        
        /// <summary>
        /// Initializes a new instance of the <see cref="T:BankAccountsComparer"/> class.
        /// </summary>
        /// <param name="column">The column to sort on.</param>
        public BankAccountsComparer(BankAccountsColumn column)
        {
            this.whichComparison = column;
        }

		/// <summary>
        /// Determines whether the specified <see cref="BankAccounts"/> instances are considered equal.
        /// </summary>
        /// <param name="a">The first <see cref="BankAccounts"/> to compare.</param>
        /// <param name="b">The second <c>BankAccounts</c> to compare.</param>
        /// <returns>true if objA is the same instance as objB or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
        public bool Equals(BankAccounts a, BankAccounts b)
        {
            return this.Compare(a, b) == 0;
        }

		/// <summary>
        /// Gets the hash code of the specified entity.
        /// </summary>
        /// <param name="entity">The entity.</param>
        /// <returns></returns>
        public int GetHashCode(BankAccounts entity)
        {
            return entity.GetHashCode();
        }

        /// <summary>
        /// Performs a case-insensitive comparison of two objects of the same type and returns a value indicating whether one is less than, equal to, or greater than the other.
        /// </summary>
        /// <param name="a">The first object to compare.</param>
        /// <param name="b">The second object to compare.</param>
        /// <returns></returns>
        public int Compare(BankAccounts a, BankAccounts b)
        {
        	EntityPropertyComparer entityPropertyComparer = new EntityPropertyComparer(this.whichComparison.ToString());
        	return entityPropertyComparer.Compare(a, b);
        }

		/// <summary>
        /// Gets or sets the column that will be used for comparison.
        /// </summary>
        /// <value>The comparison column.</value>
        public BankAccountsColumn WhichComparison
        {
            get { return this.whichComparison; }
            set { this.whichComparison = value; }
        }
	}
	
	#endregion
	
	#region BankAccountsKey Class

	/// <summary>
	/// Wraps the unique identifier values for the <see cref="BankAccounts"/> object.
	/// </summary>
	[Serializable]
	[CLSCompliant(true)]
	public class BankAccountsKey : EntityKeyBase
	{
		#region Constructors
		
		/// <summary>
		/// Initializes a new instance of the BankAccountsKey class.
		/// </summary>
		public BankAccountsKey()
		{
		}
		
		/// <summary>
		/// Initializes a new instance of the BankAccountsKey class.
		/// </summary>
		public BankAccountsKey(BankAccountsBase entity)
		{
			this.Entity = entity;

			#region Init Properties

			if ( entity != null )
			{
				this.BankAccountId = entity.BankAccountId;
			}

			#endregion
		}
		
		/// <summary>
		/// Initializes a new instance of the BankAccountsKey class.
		/// </summary>
		public BankAccountsKey(System.Int32 _bankAccountId)
		{
			#region Init Properties

			this.BankAccountId = _bankAccountId;

			#endregion
		}
		
		#endregion Constructors

		#region Properties
		
		// member variable for the Entity property
		private BankAccountsBase _entity;
		
		/// <summary>
		/// Gets or sets the Entity property.
		/// </summary>
		public BankAccountsBase Entity
		{
			get { return _entity; }
			set { _entity = value; }
		}
		
		// member variable for the BankAccountId property
		private System.Int32 _bankAccountId;
		
		/// <summary>
		/// Gets or sets the BankAccountId property.
		/// </summary>
		public System.Int32 BankAccountId
		{
			get { return _bankAccountId; }
			set
			{
				if ( this.Entity != null )
					this.Entity.BankAccountId = value;
				
				_bankAccountId = value;
			}
		}
		
		#endregion

		#region Methods
		
		/// <summary>
		/// Reads values from the supplied <see cref="IDictionary"/> object into
		/// properties of the current object.
		/// </summary>
		/// <param name="values">An <see cref="IDictionary"/> instance that contains
		/// the key/value pairs to be used as property values.</param>
		public override void Load(IDictionary values)
		{
			#region Init Properties

			if ( values != null )
			{
				BankAccountId = ( values["BankAccountId"] != null ) ? (System.Int32) EntityUtil.ChangeType(values["BankAccountId"], typeof(System.Int32)) : (int)0;
			}

			#endregion
		}

		/// <summary>
		/// Creates a new <see cref="IDictionary"/> object and populates it
		/// with the property values of the current object.
		/// </summary>
		/// <returns>A collection of name/value pairs.</returns>
		public override IDictionary ToDictionary()
		{
			IDictionary values = new Hashtable();

			#region Init Dictionary

			values.Add("BankAccountId", BankAccountId);

			#endregion Init Dictionary

			return values;
		}
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return String.Format("BankAccountId: {0}{1}",
								BankAccountId,
								System.Environment.NewLine);
		}

		#endregion Methods
	}
	
	#endregion	

	#region BankAccountsColumn Enum
	
	/// <summary>
	/// Enumerate the BankAccounts columns.
	/// </summary>
	[Serializable]
	public enum BankAccountsColumn : int
	{
		/// <summary>
		/// BankAccountId : 
		/// </summary>
		[EnumTextValue("Bank Account Id")]
		[ColumnEnum("BankAccountId", typeof(System.Int32), System.Data.DbType.Int32, true, true, false)]
		BankAccountId = 1,
		/// <summary>
		/// EmployeeId : 
		/// </summary>
		[EnumTextValue("Employee Id")]
		[ColumnEnum("EmployeeId", typeof(System.Int32), System.Data.DbType.Int32, false, false, false)]
		EmployeeId = 2,
		/// <summary>
		/// BankName : 
		/// </summary>
		[EnumTextValue("Bank Name")]
		[ColumnEnum("BankName", typeof(System.String), System.Data.DbType.String, false, false, true, 50)]
		BankName = 3,
		/// <summary>
		/// AccountNumber : 
		/// </summary>
		[EnumTextValue("Account Number")]
		[ColumnEnum("AccountNumber", typeof(System.String), System.Data.DbType.AnsiString, false, false, true, 50)]
		AccountNumber = 4,
		/// <summary>
		/// CreatedOn : 
		/// </summary>
		[EnumTextValue("Created On")]
		[ColumnEnum("CreatedOn", typeof(System.DateTime), System.Data.DbType.DateTime, false, false, true)]
		CreatedOn = 5
	}//End enum

	#endregion BankAccountsColumn Enum

} // end namespace
