
/*
	File generated by NetTiers templates [www.nettiers.net]
	Important: Do not modify this file. Edit the file Departments.cs instead.
*/

#region using directives
using System;
using System.ComponentModel;
using System.Collections;
using System.Xml.Serialization;
using System.Runtime.Serialization;

using EmployeeDB.BLL.Validation;
#endregion

namespace EmployeeDB.BLL
{
	///<summary>
	/// An object representation of the 'Departments' table. [No description found the database]	
	///</summary>
	[Serializable]
	[DataObject, CLSCompliant(true)]
	public abstract partial class DepartmentsBase : EntityBase, IDepartments, IEntityId<DepartmentsKey>, System.IComparable, System.ICloneable, ICloneableEx, IEditableObject, IComponent, INotifyPropertyChanged
	{		
		#region Variable Declarations
		
		/// <summary>
		///  Hold the inner data of the entity.
		/// </summary>
		private DepartmentsEntityData entityData;
		
		/// <summary>
		/// 	Hold the original data of the entity, as loaded from the repository.
		/// </summary>
		private DepartmentsEntityData _originalData;
		
		/// <summary>
		/// 	Hold a backup of the inner data of the entity.
		/// </summary>
		private DepartmentsEntityData backupData; 
		
		/// <summary>
		/// 	Key used if Tracking is Enabled for the <see cref="EntityLocator" />.
		/// </summary>
		private string entityTrackingKey;
		
		/// <summary>
		/// 	Hold the parent TList&lt;entity&gt; in which this entity maybe contained.
		/// </summary>
		/// <remark>Mostly used for databinding</remark>
		[NonSerialized]
		private TList<Departments> parentCollection;
		
		private bool inTxn = false;
		
		/// <summary>
		/// Occurs when a value is being changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event DepartmentsEventHandler ColumnChanging;		
		
		/// <summary>
		/// Occurs after a value has been changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event DepartmentsEventHandler ColumnChanged;
		
		#endregion Variable Declarations
		
		#region Constructors
		///<summary>
		/// Creates a new <see cref="DepartmentsBase"/> instance.
		///</summary>
		public DepartmentsBase()
		{
			this.entityData = new DepartmentsEntityData();
			this.backupData = null;
		}		
		
		///<summary>
		/// Creates a new <see cref="DepartmentsBase"/> instance.
		///</summary>
		///<param name="_departmentCode"></param>
		///<param name="_name"></param>
		///<param name="_createdOn"></param>
		public DepartmentsBase(System.String _departmentCode, System.String _name, System.DateTime? _createdOn)
		{
			this.entityData = new DepartmentsEntityData();
			this.backupData = null;

			this.DepartmentCode = _departmentCode;
			this.Name = _name;
			this.CreatedOn = _createdOn;
		}
		
		///<summary>
		/// A simple factory method to create a new <see cref="Departments"/> instance.
		///</summary>
		///<param name="_departmentCode"></param>
		///<param name="_name"></param>
		///<param name="_createdOn"></param>
		public static Departments CreateDepartments(System.String _departmentCode, System.String _name, System.DateTime? _createdOn)
		{
			Departments newDepartments = new Departments();
			newDepartments.DepartmentCode = _departmentCode;
			newDepartments.Name = _name;
			newDepartments.CreatedOn = _createdOn;
			return newDepartments;
		}
				
		#endregion Constructors
			
		#region Properties	
		
		#region Data Properties		
		/// <summary>
		/// 	Gets or sets the DepartmentCode property. 
		///		
		/// </summary>
		/// <value>This type is varchar.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		/// <exception cref="ArgumentNullException">If you attempt to set to null.</exception>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(true, false, false, 10)]
		public virtual System.String DepartmentCode
		{
			get
			{
				return this.entityData.DepartmentCode; 
			}
			
			set
			{
				if (this.entityData.DepartmentCode == value)
					return;
				
                OnPropertyChanging("DepartmentCode");                    
				OnColumnChanging(DepartmentsColumn.DepartmentCode, this.entityData.DepartmentCode);
				this.entityData.DepartmentCode = value;
				this.EntityId.DepartmentCode = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(DepartmentsColumn.DepartmentCode, this.entityData.DepartmentCode);
				OnPropertyChanged("DepartmentCode");
			}
		}
		
		/// <summary>
		/// 	Get the original value of the DepartmentCode property.
		///		
		/// </summary>
		/// <remarks>This is the original value of the DepartmentCode property.</remarks>
		/// <value>This type is varchar</value>
		[BrowsableAttribute(false)/*, XmlIgnoreAttribute()*/]
		public  virtual System.String OriginalDepartmentCode
		{
			get { return this.entityData.OriginalDepartmentCode; }
			set { this.entityData.OriginalDepartmentCode = value; }
		}
		
		/// <summary>
		/// 	Gets or sets the Name property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 100)]
		public virtual System.String Name
		{
			get
			{
				return this.entityData.Name; 
			}
			
			set
			{
				if (this.entityData.Name == value)
					return;
				
                OnPropertyChanging("Name");                    
				OnColumnChanging(DepartmentsColumn.Name, this.entityData.Name);
				this.entityData.Name = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(DepartmentsColumn.Name, this.entityData.Name);
				OnPropertyChanged("Name");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the CreatedOn property. 
		///		
		/// </summary>
		/// <value>This type is datetime.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null it is up to the developer to check using the HasValue property
		/// and perform business logic appropriately.
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.DateTime? CreatedOn
		{
			get
			{
				return this.entityData.CreatedOn; 
			}
			
			set
			{
				if (this.entityData.CreatedOn == value)
					return;
				
                OnPropertyChanging("CreatedOn");                    
				OnColumnChanging(DepartmentsColumn.CreatedOn, this.entityData.CreatedOn);
				this.entityData.CreatedOn = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(DepartmentsColumn.CreatedOn, this.entityData.CreatedOn);
				OnPropertyChanged("CreatedOn");
			}
		}
		
		#endregion Data Properties		

		#region Source Foreign Key Property
				
		#endregion
		
		#region Children Collections
	
		/// <summary>
		///	Holds a collection of EmployeeDepartments objects
		///	which are related to this object through the relation FK_EmployeeDepartments_Departments
		/// </summary>	
		[System.ComponentModel.Bindable(System.ComponentModel.BindableSupport.Yes)]
		public virtual TList<EmployeeDepartments> EmployeeDepartmentsCollection
		{
			get { return entityData.EmployeeDepartmentsCollection; }
			set { entityData.EmployeeDepartmentsCollection = value; }	
		}
		#endregion Children Collections
		
		#endregion
		#region Validation
		
		/// <summary>
		/// Assigns validation rules to this object based on model definition.
		/// </summary>
		/// <remarks>This method overrides the base class to add schema related validation.</remarks>
		protected override void AddValidationRules()
		{
			//Validation rules based on database schema.
			ValidationRules.AddRule( CommonRules.NotNull,
				new ValidationRuleArgs("DepartmentCode", "Department Code"));
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("DepartmentCode", "Department Code", 10));
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("Name", "Name", 100));
		}
   		#endregion
		
		#region Table Meta Data
		/// <summary>
		///		The name of the underlying database table.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string TableName
		{
			get { return "Departments"; }
		}
		
		/// <summary>
		///		The name of the underlying database table's columns.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string[] TableColumns
		{
			get
			{
				return new string[] {"DepartmentCode", "Name", "CreatedOn"};
			}
		}
		#endregion 
		
		#region IEditableObject
		
		#region  CancelAddNew Event
		/// <summary>
        /// The delegate for the CancelAddNew event.
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
		public delegate void CancelAddNewEventHandler(object sender, EventArgs e);
    
    	/// <summary>
		/// The CancelAddNew event.
		/// </summary>
		[field:NonSerialized]
		public event CancelAddNewEventHandler CancelAddNew ;

		/// <summary>
        /// Called when [cancel add new].
        /// </summary>
        public void OnCancelAddNew()
        {    
			if (!SuppressEntityEvents)
			{
	            CancelAddNewEventHandler handler = CancelAddNew ;
            	if (handler != null)
	            {    
    	            handler(this, EventArgs.Empty) ;
        	    }
	        }
        }
		#endregion 
		
		/// <summary>
		/// Begins an edit on an object.
		/// </summary>
		void IEditableObject.BeginEdit() 
	    {
	        //Console.WriteLine("Start BeginEdit");
	        if (!inTxn) 
	        {
	            this.backupData = this.entityData.Clone() as DepartmentsEntityData;
	            inTxn = true;
	            //Console.WriteLine("BeginEdit");
	        }
	        //Console.WriteLine("End BeginEdit");
	    }
	
		/// <summary>
		/// Discards changes since the last <c>BeginEdit</c> call.
		/// </summary>
	    void IEditableObject.CancelEdit() 
	    {
	        //Console.WriteLine("Start CancelEdit");
	        if (this.inTxn) 
	        {
	            this.entityData = this.backupData;
	            this.backupData = null;
				this.inTxn = false;

				if (this.bindingIsNew)
	        	//if (this.EntityState == EntityState.Added)
	        	{
					if (this.parentCollection != null)
						this.parentCollection.Remove( (Departments) this ) ;
				}	            
	        }
	        //Console.WriteLine("End CancelEdit");
	    }
	
		/// <summary>
		/// Pushes changes since the last <c>BeginEdit</c> or <c>IBindingList.AddNew</c> call into the underlying object.
		/// </summary>
	    void IEditableObject.EndEdit() 
	    {
	        //Console.WriteLine("Start EndEdit" + this.custData.id + this.custData.lastName);
	        if (this.inTxn) 
	        {
	            this.backupData = null;
				if (this.IsDirty) 
				{
					if (this.bindingIsNew) {
						this.EntityState = EntityState.Added;
						this.bindingIsNew = false ;
					}
					else
						if (this.EntityState == EntityState.Unchanged) 
							this.EntityState = EntityState.Changed ;
				}

				this.bindingIsNew = false ;
	            this.inTxn = false;	            
	        }
	        //Console.WriteLine("End EndEdit");
	    }
	    
	    /// <summary>
        /// Gets or sets the parent collection of this current entity, if available.
        /// </summary>
        /// <value>The parent collection.</value>
	    [XmlIgnore]
		[Browsable(false)]
	    public override object ParentCollection
	    {
	        get 
	        {
	            return this.parentCollection;
	        }
	        set 
	        {
	            this.parentCollection = value as TList<Departments>;
	        }
	    }
	    
	    /// <summary>
        /// Called when the entity is changed.
        /// </summary>
	    private void OnEntityChanged() 
	    {
	        if (!SuppressEntityEvents && !inTxn && this.parentCollection != null) 
	        {
	            this.parentCollection.EntityChanged(this as Departments);
	        }
	    }


		#endregion
		
		#region ICloneable Members
		///<summary>
		///  Returns a Typed Departments Entity 
		///</summary>
		protected virtual Departments Copy(IDictionary existingCopies)
		{
			if (existingCopies == null)
			{
				// This is the root of the tree to be copied!
				existingCopies = new Hashtable();
			}

			//shallow copy entity
			Departments copy = new Departments();
			existingCopies.Add(this, copy);
			copy.SuppressEntityEvents = true;
				copy.DepartmentCode = this.DepartmentCode;
					copy.OriginalDepartmentCode = this.OriginalDepartmentCode;
				copy.Name = this.Name;
				copy.CreatedOn = this.CreatedOn;
			
		
			//deep copy nested objects
			copy.EmployeeDepartmentsCollection = (TList<EmployeeDepartments>) MakeCopyOf(this.EmployeeDepartmentsCollection, existingCopies); 
			copy.EntityState = this.EntityState;
			copy.SuppressEntityEvents = false;
			return copy;
		}		
		
		
		
		///<summary>
		///  Returns a Typed Departments Entity 
		///</summary>
		public virtual Departments Copy()
		{
			return this.Copy(null);	
		}
		
		///<summary>
		/// ICloneable.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone()
		{
			return this.Copy(null);
		}
		
		///<summary>
		/// ICloneableEx.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone(IDictionary existingCopies)
		{
			return this.Copy(existingCopies);
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x)
		{
			if (x == null)
				return null;
				
			if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable Interface.");
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x, IDictionary existingCopies)
		{
			if (x == null)
				return null;
			
			if (x is ICloneableEx)
			{
				// Return a deep copy of the object
				return ((ICloneableEx)x).Clone(existingCopies);
			}
			else if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable or IClonableEx Interface.");
		}
		
		
		///<summary>
		///  Returns a Typed Departments Entity which is a deep copy of the current entity.
		///</summary>
		public virtual Departments DeepCopy()
		{
			return EntityHelper.Clone<Departments>(this as Departments);	
		}
		#endregion
		
		#region Methods	
			
		///<summary>
		/// Revert all changes and restore original values.
		///</summary>
		public override void CancelChanges()
		{
			IEditableObject obj = (IEditableObject) this;
			obj.CancelEdit();

			this.entityData = null;
			if (this._originalData != null)
			{
				this.entityData = this._originalData.Clone() as DepartmentsEntityData;
			}
			else
			{
				//Since this had no _originalData, then just reset the entityData with a new one.  entityData cannot be null.
				this.entityData = new DepartmentsEntityData();
			}
		}	
		
		/// <summary>
		/// Accepts the changes made to this object.
		/// </summary>
		/// <remarks>
		/// After calling this method, properties: IsDirty, IsNew are false. IsDeleted flag remains unchanged as it is handled by the parent List.
		/// </remarks>
		public override void AcceptChanges()
		{
			base.AcceptChanges();

			// we keep of the original version of the data
			this._originalData = null;
			this._originalData = this.entityData.Clone() as DepartmentsEntityData;
		}
		
		#region Comparision with original data
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="column">The column.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool IsPropertyChanged(DepartmentsColumn column)
		{
			switch(column)
			{
					case DepartmentsColumn.DepartmentCode:
					return entityData.DepartmentCode != _originalData.DepartmentCode;
					case DepartmentsColumn.Name:
					return entityData.Name != _originalData.Name;
					case DepartmentsColumn.CreatedOn:
					return entityData.CreatedOn != _originalData.CreatedOn;
			
				default:
					return false;
			}
		}
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="columnName">The column name.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public override bool IsPropertyChanged(string columnName)
		{
			return 	IsPropertyChanged(EntityHelper.GetEnumValue< DepartmentsColumn >(columnName));
		}
		
		/// <summary>
		/// Determines whether the data has changed from original.
		/// </summary>
		/// <returns>
		/// 	<c>true</c> if data has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool HasDataChanged()
		{
			bool result = false;
			result = result || entityData.DepartmentCode != _originalData.DepartmentCode;
			result = result || entityData.Name != _originalData.Name;
			result = result || entityData.CreatedOn != _originalData.CreatedOn;
			return result;
		}	
		
		///<summary>
		///  Returns a Departments Entity with the original data.
		///</summary>
		public Departments GetOriginalEntity()
		{
			if (_originalData != null)
				return CreateDepartments(
				_originalData.DepartmentCode,
				_originalData.Name,
				_originalData.CreatedOn
				);
				
			return (Departments)this.Clone();
		}
		#endregion
	
	#region Value Semantics Instance Equality
        ///<summary>
        /// Returns a value indicating whether this instance is equal to a specified object using value semantics.
        ///</summary>
        ///<param name="Object1">An object to compare to this instance.</param>
        ///<returns>true if Object1 is a <see cref="DepartmentsBase"/> and has the same value as this instance; otherwise, false.</returns>
        public override bool Equals(object Object1)
        {
			// Cast exception if Object1 is null or DbNull
			if (Object1 != null && Object1 != DBNull.Value && Object1 is DepartmentsBase)
				return ValueEquals(this, (DepartmentsBase)Object1);
			else
				return false;
        }

        /// <summary>
		/// Serves as a hash function for a particular type, suitable for use in hashing algorithms and data structures like a hash table.
        /// Provides a hash function that is appropriate for <see cref="DepartmentsBase"/> class 
        /// and that ensures a better distribution in the hash table
        /// </summary>
        /// <returns>number (hash code) that corresponds to the value of an object</returns>
        public override int GetHashCode()
        {
			return this.DepartmentCode.GetHashCode() ^ 
					((this.Name == null) ? string.Empty : this.Name.ToString()).GetHashCode() ^ 
					((this.CreatedOn == null) ? string.Empty : this.CreatedOn.ToString()).GetHashCode();
        }
		
		///<summary>
		/// Returns a value indicating whether this instance is equal to a specified object using value semantics.
		///</summary>
		///<param name="toObject">An object to compare to this instance.</param>
		///<returns>true if toObject is a <see cref="DepartmentsBase"/> and has the same value as this instance; otherwise, false.</returns>
		public virtual bool Equals(DepartmentsBase toObject)
		{
			if (toObject == null)
				return false;
			return ValueEquals(this, toObject);
		}
		#endregion
		
		///<summary>
		/// Determines whether the specified <see cref="DepartmentsBase"/> instances are considered equal using value semantics.
		///</summary>
		///<param name="Object1">The first <see cref="DepartmentsBase"/> to compare.</param>
		///<param name="Object2">The second <see cref="DepartmentsBase"/> to compare. </param>
		///<returns>true if Object1 is the same instance as Object2 or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
		public static bool ValueEquals(DepartmentsBase Object1, DepartmentsBase Object2)
		{
			// both are null
			if (Object1 == null && Object2 == null)
				return true;

			// one or the other is null, but not both
			if (Object1 == null ^ Object2 == null)
				return false;
				
			bool equal = true;
			if (Object1.DepartmentCode != Object2.DepartmentCode)
				equal = false;
			if ( Object1.Name != null && Object2.Name != null )
			{
				if (Object1.Name != Object2.Name)
					equal = false;
			}
			else if (Object1.Name == null ^ Object2.Name == null )
			{
				equal = false;
			}
			if ( Object1.CreatedOn != null && Object2.CreatedOn != null )
			{
				if (Object1.CreatedOn != Object2.CreatedOn)
					equal = false;
			}
			else if (Object1.CreatedOn == null ^ Object2.CreatedOn == null )
			{
				equal = false;
			}
					
			return equal;
		}
		
		#endregion
		
		#region IComparable Members
		///<summary>
		/// Compares this instance to a specified object and returns an indication of their relative values.
		///<param name="obj">An object to compare to this instance, or a null reference (Nothing in Visual Basic).</param>
		///</summary>
		///<returns>A signed integer that indicates the relative order of this instance and obj.</returns>
		public virtual int CompareTo(object obj)
		{
			throw new NotImplementedException();
			//return this. GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]) .CompareTo(((DepartmentsBase)obj).GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]));
		}
		
		/*
		// static method to get a Comparer object
        public static DepartmentsComparer GetComparer()
        {
            return new DepartmentsComparer();
        }
        */

        // Comparer delegates back to Departments
        // Employee uses the integer's default
        // CompareTo method
        /*
        public int CompareTo(Item rhs)
        {
            return this.Id.CompareTo(rhs.Id);
        }
        */

/*
        // Special implementation to be called by custom comparer
        public int CompareTo(Departments rhs, DepartmentsColumn which)
        {
            switch (which)
            {
            	
            	
            	case DepartmentsColumn.DepartmentCode:
            		return this.DepartmentCode.CompareTo(rhs.DepartmentCode);
            		
            		                 
            	
            	
            	case DepartmentsColumn.Name:
            		return this.Name.CompareTo(rhs.Name);
            		
            		                 
            	
            	
            	case DepartmentsColumn.CreatedOn:
            		return this.CreatedOn.Value.CompareTo(rhs.CreatedOn.Value);
            		
            		                 
            }
            return 0;
        }
        */
	
		#endregion
		
		#region IComponent Members
		
		private ISite _site = null;

		/// <summary>
		/// Gets or Sets the site where this data is located.
		/// </summary>
		[XmlIgnore]
		[SoapIgnore]
		[Browsable(false)]
		public ISite Site
		{
			get{ return this._site; }
			set{ this._site = value; }
		}

		#endregion

		#region IDisposable Members
		
		/// <summary>
		/// Notify those that care when we dispose.
		/// </summary>
		[field:NonSerialized]
		public event System.EventHandler Disposed;

		/// <summary>
		/// Clean up. Nothing here though.
		/// </summary>
		public virtual void Dispose()
		{
			this.parentCollection = null;
			this.Dispose(true);
			GC.SuppressFinalize(this);
		}
		
		/// <summary>
		/// Clean up.
		/// </summary>
		protected virtual void Dispose(bool disposing)
		{
			if (disposing)
			{
				EventHandler handler = Disposed;
				if (handler != null)
					handler(this, EventArgs.Empty);
			}
		}
		
		#endregion
				
		#region IEntityKey<DepartmentsKey> Members
		
		// member variable for the EntityId property
		private DepartmentsKey _entityId;

		/// <summary>
		/// Gets or sets the EntityId property.
		/// </summary>
		[XmlIgnore]
		public virtual DepartmentsKey EntityId
		{
			get
			{
				if ( _entityId == null )
				{
					_entityId = new DepartmentsKey(this);
				}

				return _entityId;
			}
			set
			{
				if ( value != null )
				{
					value.Entity = this;
				}
				
				_entityId = value;
			}
		}
		
		#endregion
		
		#region EntityState
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false) , XmlIgnoreAttribute()]
		public override EntityState EntityState 
		{ 
			get{ return entityData.EntityState;	 } 
			set{ entityData.EntityState = value; } 
		}
		#endregion 
		
		#region EntityTrackingKey
		///<summary>
		/// Provides the tracking key for the <see cref="EntityLocator"/>
		///</summary>
		[XmlIgnore]
		public override string EntityTrackingKey
		{
			get
			{
				if(entityTrackingKey == null)
					entityTrackingKey = new System.Text.StringBuilder("Departments")
					.Append("|").Append( this.DepartmentCode.ToString()).ToString();
				return entityTrackingKey;
			}
			set
		    {
		        if (value != null)
                    entityTrackingKey = value;
		    }
		}
		#endregion 
		
		#region ToString Method
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return string.Format(System.Globalization.CultureInfo.InvariantCulture,
				"{4}{3}- DepartmentCode: {0}{3}- Name: {1}{3}- CreatedOn: {2}{3}{5}", 
				this.DepartmentCode,
				(this.Name == null) ? string.Empty : this.Name.ToString(),
				(this.CreatedOn == null) ? string.Empty : this.CreatedOn.ToString(),
				System.Environment.NewLine, 
				this.GetType(),
				this.Error.Length == 0 ? string.Empty : string.Format("- Error: {0}\n",this.Error));
		}
		
		#endregion ToString Method
		
		#region Inner data class
		
	/// <summary>
	///		The data structure representation of the 'Departments' table.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	[EditorBrowsable(EditorBrowsableState.Never)]
	[Serializable]
	internal protected class DepartmentsEntityData : ICloneable, ICloneableEx
	{
		#region Variable Declarations
		private EntityState currentEntityState = EntityState.Added;
		
		#region Primary key(s)
		/// <summary>			
		/// DepartmentCode : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "Departments"</remarks>
		public System.String DepartmentCode;
			
		/// <summary>
		/// keep a copy of the original so it can be used for editable primary keys.
		/// </summary>
		public System.String OriginalDepartmentCode;
		
		#endregion
		
		#region Non Primary key(s)
		
		/// <summary>
		/// Name : 
		/// </summary>
		public System.String Name = null;
		
		/// <summary>
		/// CreatedOn : 
		/// </summary>
		public System.DateTime? CreatedOn = null;
		#endregion
			
		#region Source Foreign Key Property
				
		#endregion
        
		#endregion Variable Declarations

		#region Data Properties

		#region EmployeeDepartmentsCollection
		
		private TList<EmployeeDepartments> _employeeDepartmentsDepartmentCode;
		
		/// <summary>
		///	Holds a collection of entity objects
		///	which are related to this object through the relation _employeeDepartmentsDepartmentCode
		/// </summary>
		
		public TList<EmployeeDepartments> EmployeeDepartmentsCollection
		{
			get
			{
				if (_employeeDepartmentsDepartmentCode == null)
				{
				_employeeDepartmentsDepartmentCode = new TList<EmployeeDepartments>();
				}
	
				return _employeeDepartmentsDepartmentCode;
			}
			set { _employeeDepartmentsDepartmentCode = value; }
		}
		
		#endregion

		#endregion Data Properties
		#region Clone Method

		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public Object Clone()
		{
			DepartmentsEntityData _tmp = new DepartmentsEntityData();
						
			_tmp.DepartmentCode = this.DepartmentCode;
			_tmp.OriginalDepartmentCode = this.OriginalDepartmentCode;
			
			_tmp.Name = this.Name;
			_tmp.CreatedOn = this.CreatedOn;
			
			#region Source Parent Composite Entities
			#endregion
		
			#region Child Collections
			//deep copy nested objects
			if (this._employeeDepartmentsDepartmentCode != null)
				_tmp.EmployeeDepartmentsCollection = (TList<EmployeeDepartments>) MakeCopyOf(this.EmployeeDepartmentsCollection); 
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public object Clone(IDictionary existingCopies)
		{
			if (existingCopies == null)
				existingCopies = new Hashtable();
				
			DepartmentsEntityData _tmp = new DepartmentsEntityData();
						
			_tmp.DepartmentCode = this.DepartmentCode;
			_tmp.OriginalDepartmentCode = this.OriginalDepartmentCode;
			
			_tmp.Name = this.Name;
			_tmp.CreatedOn = this.CreatedOn;
			
			#region Source Parent Composite Entities
			#endregion
		
			#region Child Collections
			//deep copy nested objects
			_tmp.EmployeeDepartmentsCollection = (TList<EmployeeDepartments>) MakeCopyOf(this.EmployeeDepartmentsCollection, existingCopies); 
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		#endregion Clone Method
		
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public EntityState	EntityState
		{
			get { return currentEntityState;  }
			set { currentEntityState = value; }
		}
	
	}//End struct

		#endregion
		
				
		
		#region Events trigger
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="DepartmentsColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanging(DepartmentsColumn column)
		{
			OnColumnChanging(column, null);
			return;
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="DepartmentsColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanged(DepartmentsColumn column)
		{
			OnColumnChanged(column, null);
			return;
		} 
		
		
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="DepartmentsColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanging(DepartmentsColumn column, object value)
		{
			if(IsEntityTracked && EntityState != EntityState.Added && !EntityManager.TrackChangedEntities)
                EntityManager.StopTracking(entityTrackingKey);
                
			if (!SuppressEntityEvents)
			{
				DepartmentsEventHandler handler = ColumnChanging;
				if(handler != null)
				{
					handler(this, new DepartmentsEventArgs(column, value));
				}
			}
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="DepartmentsColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanged(DepartmentsColumn column, object value)
		{
			if (!SuppressEntityEvents)
			{
				DepartmentsEventHandler handler = ColumnChanged;
				if(handler != null)
				{
					handler(this, new DepartmentsEventArgs(column, value));
				}
			
				// warn the parent list that i have changed
				OnEntityChanged();
			}
		} 
		#endregion
			
	} // End Class
	
	
	#region DepartmentsEventArgs class
	/// <summary>
	/// Provides data for the ColumnChanging and ColumnChanged events.
	/// </summary>
	/// <remarks>
	/// The ColumnChanging and ColumnChanged events occur when a change is made to the value 
	/// of a property of a <see cref="Departments"/> object.
	/// </remarks>
	public class DepartmentsEventArgs : System.EventArgs
	{
		private DepartmentsColumn column;
		private object value;
		
		///<summary>
		/// Initalizes a new Instance of the DepartmentsEventArgs class.
		///</summary>
		public DepartmentsEventArgs(DepartmentsColumn column)
		{
			this.column = column;
		}
		
		///<summary>
		/// Initalizes a new Instance of the DepartmentsEventArgs class.
		///</summary>
		public DepartmentsEventArgs(DepartmentsColumn column, object value)
		{
			this.column = column;
			this.value = value;
		}
		
		///<summary>
		/// The DepartmentsColumn that was modified, which has raised the event.
		///</summary>
		///<value cref="DepartmentsColumn" />
		public DepartmentsColumn Column { get { return this.column; } }
		
		/// <summary>
        /// Gets the current value of the column.
        /// </summary>
        /// <value>The current value of the column.</value>
		public object Value{ get { return this.value; } }

	}
	#endregion
	
	///<summary>
	/// Define a delegate for all Departments related events.
	///</summary>
	public delegate void DepartmentsEventHandler(object sender, DepartmentsEventArgs e);
	
	#region DepartmentsComparer
		
	/// <summary>
	///	Strongly Typed IComparer
	/// </summary>
	public class DepartmentsComparer : System.Collections.Generic.IComparer<Departments>
	{
		DepartmentsColumn whichComparison;
		
		/// <summary>
        /// Initializes a new instance of the <see cref="T:DepartmentsComparer"/> class.
        /// </summary>
		public DepartmentsComparer()
        {            
        }               
        
        /// <summary>
        /// Initializes a new instance of the <see cref="T:DepartmentsComparer"/> class.
        /// </summary>
        /// <param name="column">The column to sort on.</param>
        public DepartmentsComparer(DepartmentsColumn column)
        {
            this.whichComparison = column;
        }

		/// <summary>
        /// Determines whether the specified <see cref="Departments"/> instances are considered equal.
        /// </summary>
        /// <param name="a">The first <see cref="Departments"/> to compare.</param>
        /// <param name="b">The second <c>Departments</c> to compare.</param>
        /// <returns>true if objA is the same instance as objB or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
        public bool Equals(Departments a, Departments b)
        {
            return this.Compare(a, b) == 0;
        }

		/// <summary>
        /// Gets the hash code of the specified entity.
        /// </summary>
        /// <param name="entity">The entity.</param>
        /// <returns></returns>
        public int GetHashCode(Departments entity)
        {
            return entity.GetHashCode();
        }

        /// <summary>
        /// Performs a case-insensitive comparison of two objects of the same type and returns a value indicating whether one is less than, equal to, or greater than the other.
        /// </summary>
        /// <param name="a">The first object to compare.</param>
        /// <param name="b">The second object to compare.</param>
        /// <returns></returns>
        public int Compare(Departments a, Departments b)
        {
        	EntityPropertyComparer entityPropertyComparer = new EntityPropertyComparer(this.whichComparison.ToString());
        	return entityPropertyComparer.Compare(a, b);
        }

		/// <summary>
        /// Gets or sets the column that will be used for comparison.
        /// </summary>
        /// <value>The comparison column.</value>
        public DepartmentsColumn WhichComparison
        {
            get { return this.whichComparison; }
            set { this.whichComparison = value; }
        }
	}
	
	#endregion
	
	#region DepartmentsKey Class

	/// <summary>
	/// Wraps the unique identifier values for the <see cref="Departments"/> object.
	/// </summary>
	[Serializable]
	[CLSCompliant(true)]
	public class DepartmentsKey : EntityKeyBase
	{
		#region Constructors
		
		/// <summary>
		/// Initializes a new instance of the DepartmentsKey class.
		/// </summary>
		public DepartmentsKey()
		{
		}
		
		/// <summary>
		/// Initializes a new instance of the DepartmentsKey class.
		/// </summary>
		public DepartmentsKey(DepartmentsBase entity)
		{
			this.Entity = entity;

			#region Init Properties

			if ( entity != null )
			{
				this.DepartmentCode = entity.DepartmentCode;
			}

			#endregion
		}
		
		/// <summary>
		/// Initializes a new instance of the DepartmentsKey class.
		/// </summary>
		public DepartmentsKey(System.String _departmentCode)
		{
			#region Init Properties

			this.DepartmentCode = _departmentCode;

			#endregion
		}
		
		#endregion Constructors

		#region Properties
		
		// member variable for the Entity property
		private DepartmentsBase _entity;
		
		/// <summary>
		/// Gets or sets the Entity property.
		/// </summary>
		public DepartmentsBase Entity
		{
			get { return _entity; }
			set { _entity = value; }
		}
		
		// member variable for the DepartmentCode property
		private System.String _departmentCode;
		
		/// <summary>
		/// Gets or sets the DepartmentCode property.
		/// </summary>
		public System.String DepartmentCode
		{
			get { return _departmentCode; }
			set
			{
				if ( this.Entity != null )
					this.Entity.DepartmentCode = value;
				
				_departmentCode = value;
			}
		}
		
		#endregion

		#region Methods
		
		/// <summary>
		/// Reads values from the supplied <see cref="IDictionary"/> object into
		/// properties of the current object.
		/// </summary>
		/// <param name="values">An <see cref="IDictionary"/> instance that contains
		/// the key/value pairs to be used as property values.</param>
		public override void Load(IDictionary values)
		{
			#region Init Properties

			if ( values != null )
			{
				DepartmentCode = ( values["DepartmentCode"] != null ) ? (System.String) EntityUtil.ChangeType(values["DepartmentCode"], typeof(System.String)) : string.Empty;
			}

			#endregion
		}

		/// <summary>
		/// Creates a new <see cref="IDictionary"/> object and populates it
		/// with the property values of the current object.
		/// </summary>
		/// <returns>A collection of name/value pairs.</returns>
		public override IDictionary ToDictionary()
		{
			IDictionary values = new Hashtable();

			#region Init Dictionary

			values.Add("DepartmentCode", DepartmentCode);

			#endregion Init Dictionary

			return values;
		}
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return String.Format("DepartmentCode: {0}{1}",
								DepartmentCode,
								System.Environment.NewLine);
		}

		#endregion Methods
	}
	
	#endregion	

	#region DepartmentsColumn Enum
	
	/// <summary>
	/// Enumerate the Departments columns.
	/// </summary>
	[Serializable]
	public enum DepartmentsColumn : int
	{
		/// <summary>
		/// DepartmentCode : 
		/// </summary>
		[EnumTextValue("Department Code")]
		[ColumnEnum("DepartmentCode", typeof(System.String), System.Data.DbType.AnsiString, true, false, false, 10)]
		DepartmentCode = 1,
		/// <summary>
		/// Name : 
		/// </summary>
		[EnumTextValue("Name")]
		[ColumnEnum("Name", typeof(System.String), System.Data.DbType.String, false, false, true, 100)]
		Name = 2,
		/// <summary>
		/// CreatedOn : 
		/// </summary>
		[EnumTextValue("Created On")]
		[ColumnEnum("CreatedOn", typeof(System.DateTime), System.Data.DbType.DateTime, false, false, true)]
		CreatedOn = 3
	}//End enum

	#endregion DepartmentsColumn Enum

} // end namespace
