
/*
	File generated by NetTiers templates [www.nettiers.net]
	Important: Do not modify this file. Edit the file EmployeeSalary.cs instead.
*/

#region using directives
using System;
using System.ComponentModel;
using System.Collections;
using System.Xml.Serialization;
using System.Runtime.Serialization;

using EmployeeDB.BLL.Validation;
#endregion

namespace EmployeeDB.BLL
{
	///<summary>
	/// An object representation of the 'EmployeeSalary' table. [No description found the database]	
	///</summary>
	[Serializable]
	[DataObject, CLSCompliant(true)]
	public abstract partial class EmployeeSalaryBase : EntityBase, IEmployeeSalary, IEntityId<EmployeeSalaryKey>, System.IComparable, System.ICloneable, ICloneableEx, IEditableObject, IComponent, INotifyPropertyChanged
	{		
		#region Variable Declarations
		
		/// <summary>
		///  Hold the inner data of the entity.
		/// </summary>
		private EmployeeSalaryEntityData entityData;
		
		/// <summary>
		/// 	Hold the original data of the entity, as loaded from the repository.
		/// </summary>
		private EmployeeSalaryEntityData _originalData;
		
		/// <summary>
		/// 	Hold a backup of the inner data of the entity.
		/// </summary>
		private EmployeeSalaryEntityData backupData; 
		
		/// <summary>
		/// 	Key used if Tracking is Enabled for the <see cref="EntityLocator" />.
		/// </summary>
		private string entityTrackingKey;
		
		/// <summary>
		/// 	Hold the parent TList&lt;entity&gt; in which this entity maybe contained.
		/// </summary>
		/// <remark>Mostly used for databinding</remark>
		[NonSerialized]
		private TList<EmployeeSalary> parentCollection;
		
		private bool inTxn = false;
		
		/// <summary>
		/// Occurs when a value is being changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event EmployeeSalaryEventHandler ColumnChanging;		
		
		/// <summary>
		/// Occurs after a value has been changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event EmployeeSalaryEventHandler ColumnChanged;
		
		#endregion Variable Declarations
		
		#region Constructors
		///<summary>
		/// Creates a new <see cref="EmployeeSalaryBase"/> instance.
		///</summary>
		public EmployeeSalaryBase()
		{
			this.entityData = new EmployeeSalaryEntityData();
			this.backupData = null;
		}		
		
		///<summary>
		/// Creates a new <see cref="EmployeeSalaryBase"/> instance.
		///</summary>
		///<param name="_employeeId"></param>
		///<param name="_salaryAmount"></param>
		///<param name="_approvedOn"></param>
		///<param name="_approvedBy"></param>
		///<param name="_isActive"></param>
		public EmployeeSalaryBase(System.Int32? _employeeId, System.Decimal? _salaryAmount, 
			System.DateTime? _approvedOn, System.String _approvedBy, System.Boolean? _isActive)
		{
			this.entityData = new EmployeeSalaryEntityData();
			this.backupData = null;

			this.EmployeeId = _employeeId;
			this.SalaryAmount = _salaryAmount;
			this.ApprovedOn = _approvedOn;
			this.ApprovedBy = _approvedBy;
			this.IsActive = _isActive;
		}
		
		///<summary>
		/// A simple factory method to create a new <see cref="EmployeeSalary"/> instance.
		///</summary>
		///<param name="_employeeId"></param>
		///<param name="_salaryAmount"></param>
		///<param name="_approvedOn"></param>
		///<param name="_approvedBy"></param>
		///<param name="_isActive"></param>
		public static EmployeeSalary CreateEmployeeSalary(System.Int32? _employeeId, System.Decimal? _salaryAmount, 
			System.DateTime? _approvedOn, System.String _approvedBy, System.Boolean? _isActive)
		{
			EmployeeSalary newEmployeeSalary = new EmployeeSalary();
			newEmployeeSalary.EmployeeId = _employeeId;
			newEmployeeSalary.SalaryAmount = _salaryAmount;
			newEmployeeSalary.ApprovedOn = _approvedOn;
			newEmployeeSalary.ApprovedBy = _approvedBy;
			newEmployeeSalary.IsActive = _isActive;
			return newEmployeeSalary;
		}
				
		#endregion Constructors
			
		#region Properties	
		
		#region Data Properties		
		/// <summary>
		/// 	Gets or sets the EmployeeSalaryId property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		
		




		[ReadOnlyAttribute(false)/*, XmlIgnoreAttribute()*/, DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(true, true, false)]
		public virtual System.Int32 EmployeeSalaryId
		{
			get
			{
				return this.entityData.EmployeeSalaryId; 
			}
			
			set
			{
				if (this.entityData.EmployeeSalaryId == value)
					return;
				
                OnPropertyChanging("EmployeeSalaryId");                    
				OnColumnChanging(EmployeeSalaryColumn.EmployeeSalaryId, this.entityData.EmployeeSalaryId);
				this.entityData.EmployeeSalaryId = value;
				this.EntityId.EmployeeSalaryId = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(EmployeeSalaryColumn.EmployeeSalaryId, this.entityData.EmployeeSalaryId);
				OnPropertyChanged("EmployeeSalaryId");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the EmployeeId property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null it is up to the developer to check using the HasValue property
		/// and perform business logic appropriately.
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.Int32? EmployeeId
		{
			get
			{
				return this.entityData.EmployeeId; 
			}
			
			set
			{
				if (this.entityData.EmployeeId == value)
					return;
				
                OnPropertyChanging("EmployeeId");                    
				OnColumnChanging(EmployeeSalaryColumn.EmployeeId, this.entityData.EmployeeId);
				this.entityData.EmployeeId = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(EmployeeSalaryColumn.EmployeeId, this.entityData.EmployeeId);
				OnPropertyChanged("EmployeeId");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the SalaryAmount property. 
		///		
		/// </summary>
		/// <value>This type is decimal.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null it is up to the developer to check using the HasValue property
		/// and perform business logic appropriately.
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.Decimal? SalaryAmount
		{
			get
			{
				return this.entityData.SalaryAmount; 
			}
			
			set
			{
				if (this.entityData.SalaryAmount == value)
					return;
				
                OnPropertyChanging("SalaryAmount");                    
				OnColumnChanging(EmployeeSalaryColumn.SalaryAmount, this.entityData.SalaryAmount);
				this.entityData.SalaryAmount = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(EmployeeSalaryColumn.SalaryAmount, this.entityData.SalaryAmount);
				OnPropertyChanged("SalaryAmount");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the ApprovedOn property. 
		///		
		/// </summary>
		/// <value>This type is datetime.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null it is up to the developer to check using the HasValue property
		/// and perform business logic appropriately.
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.DateTime? ApprovedOn
		{
			get
			{
				return this.entityData.ApprovedOn; 
			}
			
			set
			{
				if (this.entityData.ApprovedOn == value)
					return;
				
                OnPropertyChanging("ApprovedOn");                    
				OnColumnChanging(EmployeeSalaryColumn.ApprovedOn, this.entityData.ApprovedOn);
				this.entityData.ApprovedOn = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(EmployeeSalaryColumn.ApprovedOn, this.entityData.ApprovedOn);
				OnPropertyChanged("ApprovedOn");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the ApprovedBy property. 
		///		
		/// </summary>
		/// <value>This type is varchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 50)]
		public virtual System.String ApprovedBy
		{
			get
			{
				return this.entityData.ApprovedBy; 
			}
			
			set
			{
				if (this.entityData.ApprovedBy == value)
					return;
				
                OnPropertyChanging("ApprovedBy");                    
				OnColumnChanging(EmployeeSalaryColumn.ApprovedBy, this.entityData.ApprovedBy);
				this.entityData.ApprovedBy = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(EmployeeSalaryColumn.ApprovedBy, this.entityData.ApprovedBy);
				OnPropertyChanged("ApprovedBy");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the IsActive property. 
		///		
		/// </summary>
		/// <value>This type is bit.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null it is up to the developer to check using the HasValue property
		/// and perform business logic appropriately.
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.Boolean? IsActive
		{
			get
			{
				return this.entityData.IsActive; 
			}
			
			set
			{
				if (this.entityData.IsActive == value)
					return;
				
                OnPropertyChanging("IsActive");                    
				OnColumnChanging(EmployeeSalaryColumn.IsActive, this.entityData.IsActive);
				this.entityData.IsActive = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(EmployeeSalaryColumn.IsActive, this.entityData.IsActive);
				OnPropertyChanged("IsActive");
			}
		}
		
		#endregion Data Properties		

		#region Source Foreign Key Property
				
		/// <summary>
		/// Gets or sets the source <see cref="Employee"/>.
		/// </summary>
		/// <value>The source Employee for EmployeeId.</value>
        [XmlIgnore()]
		[Browsable(false), System.ComponentModel.Bindable(System.ComponentModel.BindableSupport.Yes)]
		public virtual Employee EmployeeIdSource
      	{
            get { return entityData.EmployeeIdSource; }
            set { entityData.EmployeeIdSource = value; }
      	}
		#endregion
		
		#region Children Collections
		#endregion Children Collections
		
		#endregion
		#region Validation
		
		/// <summary>
		/// Assigns validation rules to this object based on model definition.
		/// </summary>
		/// <remarks>This method overrides the base class to add schema related validation.</remarks>
		protected override void AddValidationRules()
		{
			//Validation rules based on database schema.
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("ApprovedBy", "Approved By", 50));
		}
   		#endregion
		
		#region Table Meta Data
		/// <summary>
		///		The name of the underlying database table.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string TableName
		{
			get { return "EmployeeSalary"; }
		}
		
		/// <summary>
		///		The name of the underlying database table's columns.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string[] TableColumns
		{
			get
			{
				return new string[] {"EmployeeSalaryId", "EmployeeId", "SalaryAmount", "ApprovedOn", "ApprovedBy", "IsActive"};
			}
		}
		#endregion 
		
		#region IEditableObject
		
		#region  CancelAddNew Event
		/// <summary>
        /// The delegate for the CancelAddNew event.
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
		public delegate void CancelAddNewEventHandler(object sender, EventArgs e);
    
    	/// <summary>
		/// The CancelAddNew event.
		/// </summary>
		[field:NonSerialized]
		public event CancelAddNewEventHandler CancelAddNew ;

		/// <summary>
        /// Called when [cancel add new].
        /// </summary>
        public void OnCancelAddNew()
        {    
			if (!SuppressEntityEvents)
			{
	            CancelAddNewEventHandler handler = CancelAddNew ;
            	if (handler != null)
	            {    
    	            handler(this, EventArgs.Empty) ;
        	    }
	        }
        }
		#endregion 
		
		/// <summary>
		/// Begins an edit on an object.
		/// </summary>
		void IEditableObject.BeginEdit() 
	    {
	        //Console.WriteLine("Start BeginEdit");
	        if (!inTxn) 
	        {
	            this.backupData = this.entityData.Clone() as EmployeeSalaryEntityData;
	            inTxn = true;
	            //Console.WriteLine("BeginEdit");
	        }
	        //Console.WriteLine("End BeginEdit");
	    }
	
		/// <summary>
		/// Discards changes since the last <c>BeginEdit</c> call.
		/// </summary>
	    void IEditableObject.CancelEdit() 
	    {
	        //Console.WriteLine("Start CancelEdit");
	        if (this.inTxn) 
	        {
	            this.entityData = this.backupData;
	            this.backupData = null;
				this.inTxn = false;

				if (this.bindingIsNew)
	        	//if (this.EntityState == EntityState.Added)
	        	{
					if (this.parentCollection != null)
						this.parentCollection.Remove( (EmployeeSalary) this ) ;
				}	            
	        }
	        //Console.WriteLine("End CancelEdit");
	    }
	
		/// <summary>
		/// Pushes changes since the last <c>BeginEdit</c> or <c>IBindingList.AddNew</c> call into the underlying object.
		/// </summary>
	    void IEditableObject.EndEdit() 
	    {
	        //Console.WriteLine("Start EndEdit" + this.custData.id + this.custData.lastName);
	        if (this.inTxn) 
	        {
	            this.backupData = null;
				if (this.IsDirty) 
				{
					if (this.bindingIsNew) {
						this.EntityState = EntityState.Added;
						this.bindingIsNew = false ;
					}
					else
						if (this.EntityState == EntityState.Unchanged) 
							this.EntityState = EntityState.Changed ;
				}

				this.bindingIsNew = false ;
	            this.inTxn = false;	            
	        }
	        //Console.WriteLine("End EndEdit");
	    }
	    
	    /// <summary>
        /// Gets or sets the parent collection of this current entity, if available.
        /// </summary>
        /// <value>The parent collection.</value>
	    [XmlIgnore]
		[Browsable(false)]
	    public override object ParentCollection
	    {
	        get 
	        {
	            return this.parentCollection;
	        }
	        set 
	        {
	            this.parentCollection = value as TList<EmployeeSalary>;
	        }
	    }
	    
	    /// <summary>
        /// Called when the entity is changed.
        /// </summary>
	    private void OnEntityChanged() 
	    {
	        if (!SuppressEntityEvents && !inTxn && this.parentCollection != null) 
	        {
	            this.parentCollection.EntityChanged(this as EmployeeSalary);
	        }
	    }


		#endregion
		
		#region ICloneable Members
		///<summary>
		///  Returns a Typed EmployeeSalary Entity 
		///</summary>
		protected virtual EmployeeSalary Copy(IDictionary existingCopies)
		{
			if (existingCopies == null)
			{
				// This is the root of the tree to be copied!
				existingCopies = new Hashtable();
			}

			//shallow copy entity
			EmployeeSalary copy = new EmployeeSalary();
			existingCopies.Add(this, copy);
			copy.SuppressEntityEvents = true;
				copy.EmployeeSalaryId = this.EmployeeSalaryId;
				copy.EmployeeId = this.EmployeeId;
				copy.SalaryAmount = this.SalaryAmount;
				copy.ApprovedOn = this.ApprovedOn;
				copy.ApprovedBy = this.ApprovedBy;
				copy.IsActive = this.IsActive;
			
			if (this.EmployeeIdSource != null && existingCopies.Contains(this.EmployeeIdSource))
				copy.EmployeeIdSource = existingCopies[this.EmployeeIdSource] as Employee;
			else
				copy.EmployeeIdSource = MakeCopyOf(this.EmployeeIdSource, existingCopies) as Employee;
		
			copy.EntityState = this.EntityState;
			copy.SuppressEntityEvents = false;
			return copy;
		}		
		
		
		
		///<summary>
		///  Returns a Typed EmployeeSalary Entity 
		///</summary>
		public virtual EmployeeSalary Copy()
		{
			return this.Copy(null);	
		}
		
		///<summary>
		/// ICloneable.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone()
		{
			return this.Copy(null);
		}
		
		///<summary>
		/// ICloneableEx.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone(IDictionary existingCopies)
		{
			return this.Copy(existingCopies);
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x)
		{
			if (x == null)
				return null;
				
			if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable Interface.");
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x, IDictionary existingCopies)
		{
			if (x == null)
				return null;
			
			if (x is ICloneableEx)
			{
				// Return a deep copy of the object
				return ((ICloneableEx)x).Clone(existingCopies);
			}
			else if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable or IClonableEx Interface.");
		}
		
		
		///<summary>
		///  Returns a Typed EmployeeSalary Entity which is a deep copy of the current entity.
		///</summary>
		public virtual EmployeeSalary DeepCopy()
		{
			return EntityHelper.Clone<EmployeeSalary>(this as EmployeeSalary);	
		}
		#endregion
		
		#region Methods	
			
		///<summary>
		/// Revert all changes and restore original values.
		///</summary>
		public override void CancelChanges()
		{
			IEditableObject obj = (IEditableObject) this;
			obj.CancelEdit();

			this.entityData = null;
			if (this._originalData != null)
			{
				this.entityData = this._originalData.Clone() as EmployeeSalaryEntityData;
			}
			else
			{
				//Since this had no _originalData, then just reset the entityData with a new one.  entityData cannot be null.
				this.entityData = new EmployeeSalaryEntityData();
			}
		}	
		
		/// <summary>
		/// Accepts the changes made to this object.
		/// </summary>
		/// <remarks>
		/// After calling this method, properties: IsDirty, IsNew are false. IsDeleted flag remains unchanged as it is handled by the parent List.
		/// </remarks>
		public override void AcceptChanges()
		{
			base.AcceptChanges();

			// we keep of the original version of the data
			this._originalData = null;
			this._originalData = this.entityData.Clone() as EmployeeSalaryEntityData;
		}
		
		#region Comparision with original data
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="column">The column.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool IsPropertyChanged(EmployeeSalaryColumn column)
		{
			switch(column)
			{
					case EmployeeSalaryColumn.EmployeeSalaryId:
					return entityData.EmployeeSalaryId != _originalData.EmployeeSalaryId;
					case EmployeeSalaryColumn.EmployeeId:
					return entityData.EmployeeId != _originalData.EmployeeId;
					case EmployeeSalaryColumn.SalaryAmount:
					return entityData.SalaryAmount != _originalData.SalaryAmount;
					case EmployeeSalaryColumn.ApprovedOn:
					return entityData.ApprovedOn != _originalData.ApprovedOn;
					case EmployeeSalaryColumn.ApprovedBy:
					return entityData.ApprovedBy != _originalData.ApprovedBy;
					case EmployeeSalaryColumn.IsActive:
					return entityData.IsActive != _originalData.IsActive;
			
				default:
					return false;
			}
		}
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="columnName">The column name.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public override bool IsPropertyChanged(string columnName)
		{
			return 	IsPropertyChanged(EntityHelper.GetEnumValue< EmployeeSalaryColumn >(columnName));
		}
		
		/// <summary>
		/// Determines whether the data has changed from original.
		/// </summary>
		/// <returns>
		/// 	<c>true</c> if data has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool HasDataChanged()
		{
			bool result = false;
			result = result || entityData.EmployeeSalaryId != _originalData.EmployeeSalaryId;
			result = result || entityData.EmployeeId != _originalData.EmployeeId;
			result = result || entityData.SalaryAmount != _originalData.SalaryAmount;
			result = result || entityData.ApprovedOn != _originalData.ApprovedOn;
			result = result || entityData.ApprovedBy != _originalData.ApprovedBy;
			result = result || entityData.IsActive != _originalData.IsActive;
			return result;
		}	
		
		///<summary>
		///  Returns a EmployeeSalary Entity with the original data.
		///</summary>
		public EmployeeSalary GetOriginalEntity()
		{
			if (_originalData != null)
				return CreateEmployeeSalary(
				_originalData.EmployeeId,
				_originalData.SalaryAmount,
				_originalData.ApprovedOn,
				_originalData.ApprovedBy,
				_originalData.IsActive
				);
				
			return (EmployeeSalary)this.Clone();
		}
		#endregion
	
	#region Value Semantics Instance Equality
        ///<summary>
        /// Returns a value indicating whether this instance is equal to a specified object using value semantics.
        ///</summary>
        ///<param name="Object1">An object to compare to this instance.</param>
        ///<returns>true if Object1 is a <see cref="EmployeeSalaryBase"/> and has the same value as this instance; otherwise, false.</returns>
        public override bool Equals(object Object1)
        {
			// Cast exception if Object1 is null or DbNull
			if (Object1 != null && Object1 != DBNull.Value && Object1 is EmployeeSalaryBase)
				return ValueEquals(this, (EmployeeSalaryBase)Object1);
			else
				return false;
        }

        /// <summary>
		/// Serves as a hash function for a particular type, suitable for use in hashing algorithms and data structures like a hash table.
        /// Provides a hash function that is appropriate for <see cref="EmployeeSalaryBase"/> class 
        /// and that ensures a better distribution in the hash table
        /// </summary>
        /// <returns>number (hash code) that corresponds to the value of an object</returns>
        public override int GetHashCode()
        {
			return this.EmployeeSalaryId.GetHashCode() ^ 
					((this.EmployeeId == null) ? string.Empty : this.EmployeeId.ToString()).GetHashCode() ^ 
					((this.SalaryAmount == null) ? string.Empty : this.SalaryAmount.ToString()).GetHashCode() ^ 
					((this.ApprovedOn == null) ? string.Empty : this.ApprovedOn.ToString()).GetHashCode() ^ 
					((this.ApprovedBy == null) ? string.Empty : this.ApprovedBy.ToString()).GetHashCode() ^ 
					((this.IsActive == null) ? string.Empty : this.IsActive.ToString()).GetHashCode();
        }
		
		///<summary>
		/// Returns a value indicating whether this instance is equal to a specified object using value semantics.
		///</summary>
		///<param name="toObject">An object to compare to this instance.</param>
		///<returns>true if toObject is a <see cref="EmployeeSalaryBase"/> and has the same value as this instance; otherwise, false.</returns>
		public virtual bool Equals(EmployeeSalaryBase toObject)
		{
			if (toObject == null)
				return false;
			return ValueEquals(this, toObject);
		}
		#endregion
		
		///<summary>
		/// Determines whether the specified <see cref="EmployeeSalaryBase"/> instances are considered equal using value semantics.
		///</summary>
		///<param name="Object1">The first <see cref="EmployeeSalaryBase"/> to compare.</param>
		///<param name="Object2">The second <see cref="EmployeeSalaryBase"/> to compare. </param>
		///<returns>true if Object1 is the same instance as Object2 or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
		public static bool ValueEquals(EmployeeSalaryBase Object1, EmployeeSalaryBase Object2)
		{
			// both are null
			if (Object1 == null && Object2 == null)
				return true;

			// one or the other is null, but not both
			if (Object1 == null ^ Object2 == null)
				return false;
				
			bool equal = true;
			if (Object1.EmployeeSalaryId != Object2.EmployeeSalaryId)
				equal = false;
			if ( Object1.EmployeeId != null && Object2.EmployeeId != null )
			{
				if (Object1.EmployeeId != Object2.EmployeeId)
					equal = false;
			}
			else if (Object1.EmployeeId == null ^ Object2.EmployeeId == null )
			{
				equal = false;
			}
			if ( Object1.SalaryAmount != null && Object2.SalaryAmount != null )
			{
				if (Object1.SalaryAmount != Object2.SalaryAmount)
					equal = false;
			}
			else if (Object1.SalaryAmount == null ^ Object2.SalaryAmount == null )
			{
				equal = false;
			}
			if ( Object1.ApprovedOn != null && Object2.ApprovedOn != null )
			{
				if (Object1.ApprovedOn != Object2.ApprovedOn)
					equal = false;
			}
			else if (Object1.ApprovedOn == null ^ Object2.ApprovedOn == null )
			{
				equal = false;
			}
			if ( Object1.ApprovedBy != null && Object2.ApprovedBy != null )
			{
				if (Object1.ApprovedBy != Object2.ApprovedBy)
					equal = false;
			}
			else if (Object1.ApprovedBy == null ^ Object2.ApprovedBy == null )
			{
				equal = false;
			}
			if ( Object1.IsActive != null && Object2.IsActive != null )
			{
				if (Object1.IsActive != Object2.IsActive)
					equal = false;
			}
			else if (Object1.IsActive == null ^ Object2.IsActive == null )
			{
				equal = false;
			}
					
			return equal;
		}
		
		#endregion
		
		#region IComparable Members
		///<summary>
		/// Compares this instance to a specified object and returns an indication of their relative values.
		///<param name="obj">An object to compare to this instance, or a null reference (Nothing in Visual Basic).</param>
		///</summary>
		///<returns>A signed integer that indicates the relative order of this instance and obj.</returns>
		public virtual int CompareTo(object obj)
		{
			throw new NotImplementedException();
			//return this. GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]) .CompareTo(((EmployeeSalaryBase)obj).GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]));
		}
		
		/*
		// static method to get a Comparer object
        public static EmployeeSalaryComparer GetComparer()
        {
            return new EmployeeSalaryComparer();
        }
        */

        // Comparer delegates back to EmployeeSalary
        // Employee uses the integer's default
        // CompareTo method
        /*
        public int CompareTo(Item rhs)
        {
            return this.Id.CompareTo(rhs.Id);
        }
        */

/*
        // Special implementation to be called by custom comparer
        public int CompareTo(EmployeeSalary rhs, EmployeeSalaryColumn which)
        {
            switch (which)
            {
            	
            	
            	case EmployeeSalaryColumn.EmployeeSalaryId:
            		return this.EmployeeSalaryId.CompareTo(rhs.EmployeeSalaryId);
            		
            		                 
            	
            	
            	case EmployeeSalaryColumn.EmployeeId:
            		return this.EmployeeId.Value.CompareTo(rhs.EmployeeId.Value);
            		
            		                 
            	
            	
            	case EmployeeSalaryColumn.SalaryAmount:
            		return this.SalaryAmount.Value.CompareTo(rhs.SalaryAmount.Value);
            		
            		                 
            	
            	
            	case EmployeeSalaryColumn.ApprovedOn:
            		return this.ApprovedOn.Value.CompareTo(rhs.ApprovedOn.Value);
            		
            		                 
            	
            	
            	case EmployeeSalaryColumn.ApprovedBy:
            		return this.ApprovedBy.CompareTo(rhs.ApprovedBy);
            		
            		                 
            	
            	
            	case EmployeeSalaryColumn.IsActive:
            		return this.IsActive.Value.CompareTo(rhs.IsActive.Value);
            		
            		                 
            }
            return 0;
        }
        */
	
		#endregion
		
		#region IComponent Members
		
		private ISite _site = null;

		/// <summary>
		/// Gets or Sets the site where this data is located.
		/// </summary>
		[XmlIgnore]
		[SoapIgnore]
		[Browsable(false)]
		public ISite Site
		{
			get{ return this._site; }
			set{ this._site = value; }
		}

		#endregion

		#region IDisposable Members
		
		/// <summary>
		/// Notify those that care when we dispose.
		/// </summary>
		[field:NonSerialized]
		public event System.EventHandler Disposed;

		/// <summary>
		/// Clean up. Nothing here though.
		/// </summary>
		public virtual void Dispose()
		{
			this.parentCollection = null;
			this.Dispose(true);
			GC.SuppressFinalize(this);
		}
		
		/// <summary>
		/// Clean up.
		/// </summary>
		protected virtual void Dispose(bool disposing)
		{
			if (disposing)
			{
				EventHandler handler = Disposed;
				if (handler != null)
					handler(this, EventArgs.Empty);
			}
		}
		
		#endregion
				
		#region IEntityKey<EmployeeSalaryKey> Members
		
		// member variable for the EntityId property
		private EmployeeSalaryKey _entityId;

		/// <summary>
		/// Gets or sets the EntityId property.
		/// </summary>
		[XmlIgnore]
		public virtual EmployeeSalaryKey EntityId
		{
			get
			{
				if ( _entityId == null )
				{
					_entityId = new EmployeeSalaryKey(this);
				}

				return _entityId;
			}
			set
			{
				if ( value != null )
				{
					value.Entity = this;
				}
				
				_entityId = value;
			}
		}
		
		#endregion
		
		#region EntityState
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false) , XmlIgnoreAttribute()]
		public override EntityState EntityState 
		{ 
			get{ return entityData.EntityState;	 } 
			set{ entityData.EntityState = value; } 
		}
		#endregion 
		
		#region EntityTrackingKey
		///<summary>
		/// Provides the tracking key for the <see cref="EntityLocator"/>
		///</summary>
		[XmlIgnore]
		public override string EntityTrackingKey
		{
			get
			{
				if(entityTrackingKey == null)
					entityTrackingKey = new System.Text.StringBuilder("EmployeeSalary")
					.Append("|").Append( this.EmployeeSalaryId.ToString()).ToString();
				return entityTrackingKey;
			}
			set
		    {
		        if (value != null)
                    entityTrackingKey = value;
		    }
		}
		#endregion 
		
		#region ToString Method
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return string.Format(System.Globalization.CultureInfo.InvariantCulture,
				"{7}{6}- EmployeeSalaryId: {0}{6}- EmployeeId: {1}{6}- SalaryAmount: {2}{6}- ApprovedOn: {3}{6}- ApprovedBy: {4}{6}- IsActive: {5}{6}{8}", 
				this.EmployeeSalaryId,
				(this.EmployeeId == null) ? string.Empty : this.EmployeeId.ToString(),
				(this.SalaryAmount == null) ? string.Empty : this.SalaryAmount.ToString(),
				(this.ApprovedOn == null) ? string.Empty : this.ApprovedOn.ToString(),
				(this.ApprovedBy == null) ? string.Empty : this.ApprovedBy.ToString(),
				(this.IsActive == null) ? string.Empty : this.IsActive.ToString(),
				System.Environment.NewLine, 
				this.GetType(),
				this.Error.Length == 0 ? string.Empty : string.Format("- Error: {0}\n",this.Error));
		}
		
		#endregion ToString Method
		
		#region Inner data class
		
	/// <summary>
	///		The data structure representation of the 'EmployeeSalary' table.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	[EditorBrowsable(EditorBrowsableState.Never)]
	[Serializable]
	internal protected class EmployeeSalaryEntityData : ICloneable, ICloneableEx
	{
		#region Variable Declarations
		private EntityState currentEntityState = EntityState.Added;
		
		#region Primary key(s)
		/// <summary>			
		/// EmployeeSalaryId : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "EmployeeSalary"</remarks>
		public System.Int32 EmployeeSalaryId;
			
		#endregion
		
		#region Non Primary key(s)
		
		/// <summary>
		/// EmployeeId : 
		/// </summary>
		public System.Int32? EmployeeId = null;
		
		/// <summary>
		/// SalaryAmount : 
		/// </summary>
		public System.Decimal? SalaryAmount = null;
		
		/// <summary>
		/// ApprovedOn : 
		/// </summary>
		public System.DateTime? ApprovedOn = null;
		
		/// <summary>
		/// ApprovedBy : 
		/// </summary>
		public System.String ApprovedBy = null;
		
		/// <summary>
		/// IsActive : 
		/// </summary>
		public System.Boolean? IsActive = null;
		#endregion
			
		#region Source Foreign Key Property
				
		private Employee _employeeIdSource = null;
		
		/// <summary>
		/// Gets or sets the source <see cref="Employee"/>.
		/// </summary>
		/// <value>The source Employee for EmployeeId.</value>
		[XmlIgnore()]
		[Browsable(false)]
		public virtual Employee EmployeeIdSource
      	{
            get { return this._employeeIdSource; }
            set { this._employeeIdSource = value; }
      	}
		#endregion
        
		#endregion Variable Declarations

		#region Data Properties

		#endregion Data Properties
		#region Clone Method

		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public Object Clone()
		{
			EmployeeSalaryEntityData _tmp = new EmployeeSalaryEntityData();
						
			_tmp.EmployeeSalaryId = this.EmployeeSalaryId;
			
			_tmp.EmployeeId = this.EmployeeId;
			_tmp.SalaryAmount = this.SalaryAmount;
			_tmp.ApprovedOn = this.ApprovedOn;
			_tmp.ApprovedBy = this.ApprovedBy;
			_tmp.IsActive = this.IsActive;
			
			#region Source Parent Composite Entities
			if (this.EmployeeIdSource != null)
				_tmp.EmployeeIdSource = MakeCopyOf(this.EmployeeIdSource) as Employee;
			#endregion
		
			#region Child Collections
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public object Clone(IDictionary existingCopies)
		{
			if (existingCopies == null)
				existingCopies = new Hashtable();
				
			EmployeeSalaryEntityData _tmp = new EmployeeSalaryEntityData();
						
			_tmp.EmployeeSalaryId = this.EmployeeSalaryId;
			
			_tmp.EmployeeId = this.EmployeeId;
			_tmp.SalaryAmount = this.SalaryAmount;
			_tmp.ApprovedOn = this.ApprovedOn;
			_tmp.ApprovedBy = this.ApprovedBy;
			_tmp.IsActive = this.IsActive;
			
			#region Source Parent Composite Entities
			if (this.EmployeeIdSource != null && existingCopies.Contains(this.EmployeeIdSource))
				_tmp.EmployeeIdSource = existingCopies[this.EmployeeIdSource] as Employee;
			else
				_tmp.EmployeeIdSource = MakeCopyOf(this.EmployeeIdSource, existingCopies) as Employee;
			#endregion
		
			#region Child Collections
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		#endregion Clone Method
		
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public EntityState	EntityState
		{
			get { return currentEntityState;  }
			set { currentEntityState = value; }
		}
	
	}//End struct

		#endregion
		
				
		
		#region Events trigger
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="EmployeeSalaryColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanging(EmployeeSalaryColumn column)
		{
			OnColumnChanging(column, null);
			return;
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="EmployeeSalaryColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanged(EmployeeSalaryColumn column)
		{
			OnColumnChanged(column, null);
			return;
		} 
		
		
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="EmployeeSalaryColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanging(EmployeeSalaryColumn column, object value)
		{
			if(IsEntityTracked && EntityState != EntityState.Added && !EntityManager.TrackChangedEntities)
                EntityManager.StopTracking(entityTrackingKey);
                
			if (!SuppressEntityEvents)
			{
				EmployeeSalaryEventHandler handler = ColumnChanging;
				if(handler != null)
				{
					handler(this, new EmployeeSalaryEventArgs(column, value));
				}
			}
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="EmployeeSalaryColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanged(EmployeeSalaryColumn column, object value)
		{
			if (!SuppressEntityEvents)
			{
				EmployeeSalaryEventHandler handler = ColumnChanged;
				if(handler != null)
				{
					handler(this, new EmployeeSalaryEventArgs(column, value));
				}
			
				// warn the parent list that i have changed
				OnEntityChanged();
			}
		} 
		#endregion
			
	} // End Class
	
	
	#region EmployeeSalaryEventArgs class
	/// <summary>
	/// Provides data for the ColumnChanging and ColumnChanged events.
	/// </summary>
	/// <remarks>
	/// The ColumnChanging and ColumnChanged events occur when a change is made to the value 
	/// of a property of a <see cref="EmployeeSalary"/> object.
	/// </remarks>
	public class EmployeeSalaryEventArgs : System.EventArgs
	{
		private EmployeeSalaryColumn column;
		private object value;
		
		///<summary>
		/// Initalizes a new Instance of the EmployeeSalaryEventArgs class.
		///</summary>
		public EmployeeSalaryEventArgs(EmployeeSalaryColumn column)
		{
			this.column = column;
		}
		
		///<summary>
		/// Initalizes a new Instance of the EmployeeSalaryEventArgs class.
		///</summary>
		public EmployeeSalaryEventArgs(EmployeeSalaryColumn column, object value)
		{
			this.column = column;
			this.value = value;
		}
		
		///<summary>
		/// The EmployeeSalaryColumn that was modified, which has raised the event.
		///</summary>
		///<value cref="EmployeeSalaryColumn" />
		public EmployeeSalaryColumn Column { get { return this.column; } }
		
		/// <summary>
        /// Gets the current value of the column.
        /// </summary>
        /// <value>The current value of the column.</value>
		public object Value{ get { return this.value; } }

	}
	#endregion
	
	///<summary>
	/// Define a delegate for all EmployeeSalary related events.
	///</summary>
	public delegate void EmployeeSalaryEventHandler(object sender, EmployeeSalaryEventArgs e);
	
	#region EmployeeSalaryComparer
		
	/// <summary>
	///	Strongly Typed IComparer
	/// </summary>
	public class EmployeeSalaryComparer : System.Collections.Generic.IComparer<EmployeeSalary>
	{
		EmployeeSalaryColumn whichComparison;
		
		/// <summary>
        /// Initializes a new instance of the <see cref="T:EmployeeSalaryComparer"/> class.
        /// </summary>
		public EmployeeSalaryComparer()
        {            
        }               
        
        /// <summary>
        /// Initializes a new instance of the <see cref="T:EmployeeSalaryComparer"/> class.
        /// </summary>
        /// <param name="column">The column to sort on.</param>
        public EmployeeSalaryComparer(EmployeeSalaryColumn column)
        {
            this.whichComparison = column;
        }

		/// <summary>
        /// Determines whether the specified <see cref="EmployeeSalary"/> instances are considered equal.
        /// </summary>
        /// <param name="a">The first <see cref="EmployeeSalary"/> to compare.</param>
        /// <param name="b">The second <c>EmployeeSalary</c> to compare.</param>
        /// <returns>true if objA is the same instance as objB or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
        public bool Equals(EmployeeSalary a, EmployeeSalary b)
        {
            return this.Compare(a, b) == 0;
        }

		/// <summary>
        /// Gets the hash code of the specified entity.
        /// </summary>
        /// <param name="entity">The entity.</param>
        /// <returns></returns>
        public int GetHashCode(EmployeeSalary entity)
        {
            return entity.GetHashCode();
        }

        /// <summary>
        /// Performs a case-insensitive comparison of two objects of the same type and returns a value indicating whether one is less than, equal to, or greater than the other.
        /// </summary>
        /// <param name="a">The first object to compare.</param>
        /// <param name="b">The second object to compare.</param>
        /// <returns></returns>
        public int Compare(EmployeeSalary a, EmployeeSalary b)
        {
        	EntityPropertyComparer entityPropertyComparer = new EntityPropertyComparer(this.whichComparison.ToString());
        	return entityPropertyComparer.Compare(a, b);
        }

		/// <summary>
        /// Gets or sets the column that will be used for comparison.
        /// </summary>
        /// <value>The comparison column.</value>
        public EmployeeSalaryColumn WhichComparison
        {
            get { return this.whichComparison; }
            set { this.whichComparison = value; }
        }
	}
	
	#endregion
	
	#region EmployeeSalaryKey Class

	/// <summary>
	/// Wraps the unique identifier values for the <see cref="EmployeeSalary"/> object.
	/// </summary>
	[Serializable]
	[CLSCompliant(true)]
	public class EmployeeSalaryKey : EntityKeyBase
	{
		#region Constructors
		
		/// <summary>
		/// Initializes a new instance of the EmployeeSalaryKey class.
		/// </summary>
		public EmployeeSalaryKey()
		{
		}
		
		/// <summary>
		/// Initializes a new instance of the EmployeeSalaryKey class.
		/// </summary>
		public EmployeeSalaryKey(EmployeeSalaryBase entity)
		{
			this.Entity = entity;

			#region Init Properties

			if ( entity != null )
			{
				this.EmployeeSalaryId = entity.EmployeeSalaryId;
			}

			#endregion
		}
		
		/// <summary>
		/// Initializes a new instance of the EmployeeSalaryKey class.
		/// </summary>
		public EmployeeSalaryKey(System.Int32 _employeeSalaryId)
		{
			#region Init Properties

			this.EmployeeSalaryId = _employeeSalaryId;

			#endregion
		}
		
		#endregion Constructors

		#region Properties
		
		// member variable for the Entity property
		private EmployeeSalaryBase _entity;
		
		/// <summary>
		/// Gets or sets the Entity property.
		/// </summary>
		public EmployeeSalaryBase Entity
		{
			get { return _entity; }
			set { _entity = value; }
		}
		
		// member variable for the EmployeeSalaryId property
		private System.Int32 _employeeSalaryId;
		
		/// <summary>
		/// Gets or sets the EmployeeSalaryId property.
		/// </summary>
		public System.Int32 EmployeeSalaryId
		{
			get { return _employeeSalaryId; }
			set
			{
				if ( this.Entity != null )
					this.Entity.EmployeeSalaryId = value;
				
				_employeeSalaryId = value;
			}
		}
		
		#endregion

		#region Methods
		
		/// <summary>
		/// Reads values from the supplied <see cref="IDictionary"/> object into
		/// properties of the current object.
		/// </summary>
		/// <param name="values">An <see cref="IDictionary"/> instance that contains
		/// the key/value pairs to be used as property values.</param>
		public override void Load(IDictionary values)
		{
			#region Init Properties

			if ( values != null )
			{
				EmployeeSalaryId = ( values["EmployeeSalaryId"] != null ) ? (System.Int32) EntityUtil.ChangeType(values["EmployeeSalaryId"], typeof(System.Int32)) : (int)0;
			}

			#endregion
		}

		/// <summary>
		/// Creates a new <see cref="IDictionary"/> object and populates it
		/// with the property values of the current object.
		/// </summary>
		/// <returns>A collection of name/value pairs.</returns>
		public override IDictionary ToDictionary()
		{
			IDictionary values = new Hashtable();

			#region Init Dictionary

			values.Add("EmployeeSalaryId", EmployeeSalaryId);

			#endregion Init Dictionary

			return values;
		}
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return String.Format("EmployeeSalaryId: {0}{1}",
								EmployeeSalaryId,
								System.Environment.NewLine);
		}

		#endregion Methods
	}
	
	#endregion	

	#region EmployeeSalaryColumn Enum
	
	/// <summary>
	/// Enumerate the EmployeeSalary columns.
	/// </summary>
	[Serializable]
	public enum EmployeeSalaryColumn : int
	{
		/// <summary>
		/// EmployeeSalaryId : 
		/// </summary>
		[EnumTextValue("Employee Salary Id")]
		[ColumnEnum("EmployeeSalaryId", typeof(System.Int32), System.Data.DbType.Int32, true, true, false)]
		EmployeeSalaryId = 1,
		/// <summary>
		/// EmployeeId : 
		/// </summary>
		[EnumTextValue("Employee Id")]
		[ColumnEnum("EmployeeId", typeof(System.Int32), System.Data.DbType.Int32, false, false, true)]
		EmployeeId = 2,
		/// <summary>
		/// SalaryAmount : 
		/// </summary>
		[EnumTextValue("Salary Amount")]
		[ColumnEnum("SalaryAmount", typeof(System.Decimal), System.Data.DbType.Decimal, false, false, true)]
		SalaryAmount = 3,
		/// <summary>
		/// ApprovedOn : 
		/// </summary>
		[EnumTextValue("Approved On")]
		[ColumnEnum("ApprovedOn", typeof(System.DateTime), System.Data.DbType.DateTime, false, false, true)]
		ApprovedOn = 4,
		/// <summary>
		/// ApprovedBy : 
		/// </summary>
		[EnumTextValue("Approved By")]
		[ColumnEnum("ApprovedBy", typeof(System.String), System.Data.DbType.AnsiString, false, false, true, 50)]
		ApprovedBy = 5,
		/// <summary>
		/// IsActive : 
		/// </summary>
		[EnumTextValue("Is Active")]
		[ColumnEnum("IsActive", typeof(System.Boolean), System.Data.DbType.Boolean, false, false, true)]
		IsActive = 6
	}//End enum

	#endregion EmployeeSalaryColumn Enum

} // end namespace
