
/*
	File generated by NetTiers templates [www.nettiers.net]
	Important: Do not modify this file. Edit the file EmployeeSkills.cs instead.
*/

#region using directives
using System;
using System.ComponentModel;
using System.Collections;
using System.Xml.Serialization;
using System.Runtime.Serialization;

using EmployeeDB.BLL.Validation;
#endregion

namespace EmployeeDB.BLL
{
	///<summary>
	/// An object representation of the 'EmployeeSkills' table. [No description found the database]	
	///</summary>
	[Serializable]
	[DataObject, CLSCompliant(true)]
	public abstract partial class EmployeeSkillsBase : EntityBase, IEmployeeSkills, IEntityId<EmployeeSkillsKey>, System.IComparable, System.ICloneable, ICloneableEx, IEditableObject, IComponent, INotifyPropertyChanged
	{		
		#region Variable Declarations
		
		/// <summary>
		///  Hold the inner data of the entity.
		/// </summary>
		private EmployeeSkillsEntityData entityData;
		
		/// <summary>
		/// 	Hold the original data of the entity, as loaded from the repository.
		/// </summary>
		private EmployeeSkillsEntityData _originalData;
		
		/// <summary>
		/// 	Hold a backup of the inner data of the entity.
		/// </summary>
		private EmployeeSkillsEntityData backupData; 
		
		/// <summary>
		/// 	Key used if Tracking is Enabled for the <see cref="EntityLocator" />.
		/// </summary>
		private string entityTrackingKey;
		
		/// <summary>
		/// 	Hold the parent TList&lt;entity&gt; in which this entity maybe contained.
		/// </summary>
		/// <remark>Mostly used for databinding</remark>
		[NonSerialized]
		private TList<EmployeeSkills> parentCollection;
		
		private bool inTxn = false;
		
		/// <summary>
		/// Occurs when a value is being changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event EmployeeSkillsEventHandler ColumnChanging;		
		
		/// <summary>
		/// Occurs after a value has been changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event EmployeeSkillsEventHandler ColumnChanged;
		
		#endregion Variable Declarations
		
		#region Constructors
		///<summary>
		/// Creates a new <see cref="EmployeeSkillsBase"/> instance.
		///</summary>
		public EmployeeSkillsBase()
		{
			this.entityData = new EmployeeSkillsEntityData();
			this.backupData = null;
		}		
		
		///<summary>
		/// Creates a new <see cref="EmployeeSkillsBase"/> instance.
		///</summary>
		///<param name="_employeeId"></param>
		///<param name="_skillCode"></param>
		///<param name="_skillLevel"></param>
		///<param name="_createdOn"></param>
		public EmployeeSkillsBase(System.Int32? _employeeId, System.String _skillCode, System.String _skillLevel, 
			System.DateTime? _createdOn)
		{
			this.entityData = new EmployeeSkillsEntityData();
			this.backupData = null;

			this.EmployeeId = _employeeId;
			this.SkillCode = _skillCode;
			this.SkillLevel = _skillLevel;
			this.CreatedOn = _createdOn;
		}
		
		///<summary>
		/// A simple factory method to create a new <see cref="EmployeeSkills"/> instance.
		///</summary>
		///<param name="_employeeId"></param>
		///<param name="_skillCode"></param>
		///<param name="_skillLevel"></param>
		///<param name="_createdOn"></param>
		public static EmployeeSkills CreateEmployeeSkills(System.Int32? _employeeId, System.String _skillCode, System.String _skillLevel, 
			System.DateTime? _createdOn)
		{
			EmployeeSkills newEmployeeSkills = new EmployeeSkills();
			newEmployeeSkills.EmployeeId = _employeeId;
			newEmployeeSkills.SkillCode = _skillCode;
			newEmployeeSkills.SkillLevel = _skillLevel;
			newEmployeeSkills.CreatedOn = _createdOn;
			return newEmployeeSkills;
		}
				
		#endregion Constructors
			
		#region Properties	
		
		#region Data Properties		
		/// <summary>
		/// 	Gets or sets the EmployeeSkillId property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		
		




		[ReadOnlyAttribute(false)/*, XmlIgnoreAttribute()*/, DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(true, true, false)]
		public virtual System.Int32 EmployeeSkillId
		{
			get
			{
				return this.entityData.EmployeeSkillId; 
			}
			
			set
			{
				if (this.entityData.EmployeeSkillId == value)
					return;
				
                OnPropertyChanging("EmployeeSkillId");                    
				OnColumnChanging(EmployeeSkillsColumn.EmployeeSkillId, this.entityData.EmployeeSkillId);
				this.entityData.EmployeeSkillId = value;
				this.EntityId.EmployeeSkillId = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(EmployeeSkillsColumn.EmployeeSkillId, this.entityData.EmployeeSkillId);
				OnPropertyChanged("EmployeeSkillId");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the EmployeeId property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null it is up to the developer to check using the HasValue property
		/// and perform business logic appropriately.
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.Int32? EmployeeId
		{
			get
			{
				return this.entityData.EmployeeId; 
			}
			
			set
			{
				if (this.entityData.EmployeeId == value)
					return;
				
                OnPropertyChanging("EmployeeId");                    
				OnColumnChanging(EmployeeSkillsColumn.EmployeeId, this.entityData.EmployeeId);
				this.entityData.EmployeeId = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(EmployeeSkillsColumn.EmployeeId, this.entityData.EmployeeId);
				OnPropertyChanged("EmployeeId");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the SkillCode property. 
		///		
		/// </summary>
		/// <value>This type is varchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 10)]
		public virtual System.String SkillCode
		{
			get
			{
				return this.entityData.SkillCode; 
			}
			
			set
			{
				if (this.entityData.SkillCode == value)
					return;
				
                OnPropertyChanging("SkillCode");                    
				OnColumnChanging(EmployeeSkillsColumn.SkillCode, this.entityData.SkillCode);
				this.entityData.SkillCode = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(EmployeeSkillsColumn.SkillCode, this.entityData.SkillCode);
				OnPropertyChanged("SkillCode");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the SkillLevel property. 
		///		
		/// </summary>
		/// <value>This type is varchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 10)]
		public virtual System.String SkillLevel
		{
			get
			{
				return this.entityData.SkillLevel; 
			}
			
			set
			{
				if (this.entityData.SkillLevel == value)
					return;
				
                OnPropertyChanging("SkillLevel");                    
				OnColumnChanging(EmployeeSkillsColumn.SkillLevel, this.entityData.SkillLevel);
				this.entityData.SkillLevel = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(EmployeeSkillsColumn.SkillLevel, this.entityData.SkillLevel);
				OnPropertyChanged("SkillLevel");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the CreatedOn property. 
		///		
		/// </summary>
		/// <value>This type is datetime.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null it is up to the developer to check using the HasValue property
		/// and perform business logic appropriately.
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.DateTime? CreatedOn
		{
			get
			{
				return this.entityData.CreatedOn; 
			}
			
			set
			{
				if (this.entityData.CreatedOn == value)
					return;
				
                OnPropertyChanging("CreatedOn");                    
				OnColumnChanging(EmployeeSkillsColumn.CreatedOn, this.entityData.CreatedOn);
				this.entityData.CreatedOn = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(EmployeeSkillsColumn.CreatedOn, this.entityData.CreatedOn);
				OnPropertyChanged("CreatedOn");
			}
		}
		
		#endregion Data Properties		

		#region Source Foreign Key Property
				
		/// <summary>
		/// Gets or sets the source <see cref="Skill"/>.
		/// </summary>
		/// <value>The source Skill for SkillCode.</value>
        [XmlIgnore()]
		[Browsable(false), System.ComponentModel.Bindable(System.ComponentModel.BindableSupport.Yes)]
		public virtual Skill SkillCodeSource
      	{
            get { return entityData.SkillCodeSource; }
            set { entityData.SkillCodeSource = value; }
      	}
		/// <summary>
		/// Gets or sets the source <see cref="SkillLevels"/>.
		/// </summary>
		/// <value>The source SkillLevels for SkillLevel.</value>
        [XmlIgnore()]
		[Browsable(false), System.ComponentModel.Bindable(System.ComponentModel.BindableSupport.Yes)]
		public virtual SkillLevels SkillLevelSource
      	{
            get { return entityData.SkillLevelSource; }
            set { entityData.SkillLevelSource = value; }
      	}
		/// <summary>
		/// Gets or sets the source <see cref="Employee"/>.
		/// </summary>
		/// <value>The source Employee for EmployeeId.</value>
        [XmlIgnore()]
		[Browsable(false), System.ComponentModel.Bindable(System.ComponentModel.BindableSupport.Yes)]
		public virtual Employee EmployeeIdSource
      	{
            get { return entityData.EmployeeIdSource; }
            set { entityData.EmployeeIdSource = value; }
      	}
		#endregion
		
		#region Children Collections
		#endregion Children Collections
		
		#endregion
		#region Validation
		
		/// <summary>
		/// Assigns validation rules to this object based on model definition.
		/// </summary>
		/// <remarks>This method overrides the base class to add schema related validation.</remarks>
		protected override void AddValidationRules()
		{
			//Validation rules based on database schema.
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("SkillCode", "Skill Code", 10));
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("SkillLevel", "Skill Level", 10));
		}
   		#endregion
		
		#region Table Meta Data
		/// <summary>
		///		The name of the underlying database table.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string TableName
		{
			get { return "EmployeeSkills"; }
		}
		
		/// <summary>
		///		The name of the underlying database table's columns.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string[] TableColumns
		{
			get
			{
				return new string[] {"EmployeeSkillId", "EmployeeId", "SkillCode", "SkillLevel", "CreatedOn"};
			}
		}
		#endregion 
		
		#region IEditableObject
		
		#region  CancelAddNew Event
		/// <summary>
        /// The delegate for the CancelAddNew event.
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
		public delegate void CancelAddNewEventHandler(object sender, EventArgs e);
    
    	/// <summary>
		/// The CancelAddNew event.
		/// </summary>
		[field:NonSerialized]
		public event CancelAddNewEventHandler CancelAddNew ;

		/// <summary>
        /// Called when [cancel add new].
        /// </summary>
        public void OnCancelAddNew()
        {    
			if (!SuppressEntityEvents)
			{
	            CancelAddNewEventHandler handler = CancelAddNew ;
            	if (handler != null)
	            {    
    	            handler(this, EventArgs.Empty) ;
        	    }
	        }
        }
		#endregion 
		
		/// <summary>
		/// Begins an edit on an object.
		/// </summary>
		void IEditableObject.BeginEdit() 
	    {
	        //Console.WriteLine("Start BeginEdit");
	        if (!inTxn) 
	        {
	            this.backupData = this.entityData.Clone() as EmployeeSkillsEntityData;
	            inTxn = true;
	            //Console.WriteLine("BeginEdit");
	        }
	        //Console.WriteLine("End BeginEdit");
	    }
	
		/// <summary>
		/// Discards changes since the last <c>BeginEdit</c> call.
		/// </summary>
	    void IEditableObject.CancelEdit() 
	    {
	        //Console.WriteLine("Start CancelEdit");
	        if (this.inTxn) 
	        {
	            this.entityData = this.backupData;
	            this.backupData = null;
				this.inTxn = false;

				if (this.bindingIsNew)
	        	//if (this.EntityState == EntityState.Added)
	        	{
					if (this.parentCollection != null)
						this.parentCollection.Remove( (EmployeeSkills) this ) ;
				}	            
	        }
	        //Console.WriteLine("End CancelEdit");
	    }
	
		/// <summary>
		/// Pushes changes since the last <c>BeginEdit</c> or <c>IBindingList.AddNew</c> call into the underlying object.
		/// </summary>
	    void IEditableObject.EndEdit() 
	    {
	        //Console.WriteLine("Start EndEdit" + this.custData.id + this.custData.lastName);
	        if (this.inTxn) 
	        {
	            this.backupData = null;
				if (this.IsDirty) 
				{
					if (this.bindingIsNew) {
						this.EntityState = EntityState.Added;
						this.bindingIsNew = false ;
					}
					else
						if (this.EntityState == EntityState.Unchanged) 
							this.EntityState = EntityState.Changed ;
				}

				this.bindingIsNew = false ;
	            this.inTxn = false;	            
	        }
	        //Console.WriteLine("End EndEdit");
	    }
	    
	    /// <summary>
        /// Gets or sets the parent collection of this current entity, if available.
        /// </summary>
        /// <value>The parent collection.</value>
	    [XmlIgnore]
		[Browsable(false)]
	    public override object ParentCollection
	    {
	        get 
	        {
	            return this.parentCollection;
	        }
	        set 
	        {
	            this.parentCollection = value as TList<EmployeeSkills>;
	        }
	    }
	    
	    /// <summary>
        /// Called when the entity is changed.
        /// </summary>
	    private void OnEntityChanged() 
	    {
	        if (!SuppressEntityEvents && !inTxn && this.parentCollection != null) 
	        {
	            this.parentCollection.EntityChanged(this as EmployeeSkills);
	        }
	    }


		#endregion
		
		#region ICloneable Members
		///<summary>
		///  Returns a Typed EmployeeSkills Entity 
		///</summary>
		protected virtual EmployeeSkills Copy(IDictionary existingCopies)
		{
			if (existingCopies == null)
			{
				// This is the root of the tree to be copied!
				existingCopies = new Hashtable();
			}

			//shallow copy entity
			EmployeeSkills copy = new EmployeeSkills();
			existingCopies.Add(this, copy);
			copy.SuppressEntityEvents = true;
				copy.EmployeeSkillId = this.EmployeeSkillId;
				copy.EmployeeId = this.EmployeeId;
				copy.SkillCode = this.SkillCode;
				copy.SkillLevel = this.SkillLevel;
				copy.CreatedOn = this.CreatedOn;
			
			if (this.SkillCodeSource != null && existingCopies.Contains(this.SkillCodeSource))
				copy.SkillCodeSource = existingCopies[this.SkillCodeSource] as Skill;
			else
				copy.SkillCodeSource = MakeCopyOf(this.SkillCodeSource, existingCopies) as Skill;
			if (this.SkillLevelSource != null && existingCopies.Contains(this.SkillLevelSource))
				copy.SkillLevelSource = existingCopies[this.SkillLevelSource] as SkillLevels;
			else
				copy.SkillLevelSource = MakeCopyOf(this.SkillLevelSource, existingCopies) as SkillLevels;
			if (this.EmployeeIdSource != null && existingCopies.Contains(this.EmployeeIdSource))
				copy.EmployeeIdSource = existingCopies[this.EmployeeIdSource] as Employee;
			else
				copy.EmployeeIdSource = MakeCopyOf(this.EmployeeIdSource, existingCopies) as Employee;
		
			copy.EntityState = this.EntityState;
			copy.SuppressEntityEvents = false;
			return copy;
		}		
		
		
		
		///<summary>
		///  Returns a Typed EmployeeSkills Entity 
		///</summary>
		public virtual EmployeeSkills Copy()
		{
			return this.Copy(null);	
		}
		
		///<summary>
		/// ICloneable.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone()
		{
			return this.Copy(null);
		}
		
		///<summary>
		/// ICloneableEx.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone(IDictionary existingCopies)
		{
			return this.Copy(existingCopies);
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x)
		{
			if (x == null)
				return null;
				
			if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable Interface.");
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x, IDictionary existingCopies)
		{
			if (x == null)
				return null;
			
			if (x is ICloneableEx)
			{
				// Return a deep copy of the object
				return ((ICloneableEx)x).Clone(existingCopies);
			}
			else if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable or IClonableEx Interface.");
		}
		
		
		///<summary>
		///  Returns a Typed EmployeeSkills Entity which is a deep copy of the current entity.
		///</summary>
		public virtual EmployeeSkills DeepCopy()
		{
			return EntityHelper.Clone<EmployeeSkills>(this as EmployeeSkills);	
		}
		#endregion
		
		#region Methods	
			
		///<summary>
		/// Revert all changes and restore original values.
		///</summary>
		public override void CancelChanges()
		{
			IEditableObject obj = (IEditableObject) this;
			obj.CancelEdit();

			this.entityData = null;
			if (this._originalData != null)
			{
				this.entityData = this._originalData.Clone() as EmployeeSkillsEntityData;
			}
			else
			{
				//Since this had no _originalData, then just reset the entityData with a new one.  entityData cannot be null.
				this.entityData = new EmployeeSkillsEntityData();
			}
		}	
		
		/// <summary>
		/// Accepts the changes made to this object.
		/// </summary>
		/// <remarks>
		/// After calling this method, properties: IsDirty, IsNew are false. IsDeleted flag remains unchanged as it is handled by the parent List.
		/// </remarks>
		public override void AcceptChanges()
		{
			base.AcceptChanges();

			// we keep of the original version of the data
			this._originalData = null;
			this._originalData = this.entityData.Clone() as EmployeeSkillsEntityData;
		}
		
		#region Comparision with original data
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="column">The column.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool IsPropertyChanged(EmployeeSkillsColumn column)
		{
			switch(column)
			{
					case EmployeeSkillsColumn.EmployeeSkillId:
					return entityData.EmployeeSkillId != _originalData.EmployeeSkillId;
					case EmployeeSkillsColumn.EmployeeId:
					return entityData.EmployeeId != _originalData.EmployeeId;
					case EmployeeSkillsColumn.SkillCode:
					return entityData.SkillCode != _originalData.SkillCode;
					case EmployeeSkillsColumn.SkillLevel:
					return entityData.SkillLevel != _originalData.SkillLevel;
					case EmployeeSkillsColumn.CreatedOn:
					return entityData.CreatedOn != _originalData.CreatedOn;
			
				default:
					return false;
			}
		}
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="columnName">The column name.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public override bool IsPropertyChanged(string columnName)
		{
			return 	IsPropertyChanged(EntityHelper.GetEnumValue< EmployeeSkillsColumn >(columnName));
		}
		
		/// <summary>
		/// Determines whether the data has changed from original.
		/// </summary>
		/// <returns>
		/// 	<c>true</c> if data has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool HasDataChanged()
		{
			bool result = false;
			result = result || entityData.EmployeeSkillId != _originalData.EmployeeSkillId;
			result = result || entityData.EmployeeId != _originalData.EmployeeId;
			result = result || entityData.SkillCode != _originalData.SkillCode;
			result = result || entityData.SkillLevel != _originalData.SkillLevel;
			result = result || entityData.CreatedOn != _originalData.CreatedOn;
			return result;
		}	
		
		///<summary>
		///  Returns a EmployeeSkills Entity with the original data.
		///</summary>
		public EmployeeSkills GetOriginalEntity()
		{
			if (_originalData != null)
				return CreateEmployeeSkills(
				_originalData.EmployeeId,
				_originalData.SkillCode,
				_originalData.SkillLevel,
				_originalData.CreatedOn
				);
				
			return (EmployeeSkills)this.Clone();
		}
		#endregion
	
	#region Value Semantics Instance Equality
        ///<summary>
        /// Returns a value indicating whether this instance is equal to a specified object using value semantics.
        ///</summary>
        ///<param name="Object1">An object to compare to this instance.</param>
        ///<returns>true if Object1 is a <see cref="EmployeeSkillsBase"/> and has the same value as this instance; otherwise, false.</returns>
        public override bool Equals(object Object1)
        {
			// Cast exception if Object1 is null or DbNull
			if (Object1 != null && Object1 != DBNull.Value && Object1 is EmployeeSkillsBase)
				return ValueEquals(this, (EmployeeSkillsBase)Object1);
			else
				return false;
        }

        /// <summary>
		/// Serves as a hash function for a particular type, suitable for use in hashing algorithms and data structures like a hash table.
        /// Provides a hash function that is appropriate for <see cref="EmployeeSkillsBase"/> class 
        /// and that ensures a better distribution in the hash table
        /// </summary>
        /// <returns>number (hash code) that corresponds to the value of an object</returns>
        public override int GetHashCode()
        {
			return this.EmployeeSkillId.GetHashCode() ^ 
					((this.EmployeeId == null) ? string.Empty : this.EmployeeId.ToString()).GetHashCode() ^ 
					((this.SkillCode == null) ? string.Empty : this.SkillCode.ToString()).GetHashCode() ^ 
					((this.SkillLevel == null) ? string.Empty : this.SkillLevel.ToString()).GetHashCode() ^ 
					((this.CreatedOn == null) ? string.Empty : this.CreatedOn.ToString()).GetHashCode();
        }
		
		///<summary>
		/// Returns a value indicating whether this instance is equal to a specified object using value semantics.
		///</summary>
		///<param name="toObject">An object to compare to this instance.</param>
		///<returns>true if toObject is a <see cref="EmployeeSkillsBase"/> and has the same value as this instance; otherwise, false.</returns>
		public virtual bool Equals(EmployeeSkillsBase toObject)
		{
			if (toObject == null)
				return false;
			return ValueEquals(this, toObject);
		}
		#endregion
		
		///<summary>
		/// Determines whether the specified <see cref="EmployeeSkillsBase"/> instances are considered equal using value semantics.
		///</summary>
		///<param name="Object1">The first <see cref="EmployeeSkillsBase"/> to compare.</param>
		///<param name="Object2">The second <see cref="EmployeeSkillsBase"/> to compare. </param>
		///<returns>true if Object1 is the same instance as Object2 or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
		public static bool ValueEquals(EmployeeSkillsBase Object1, EmployeeSkillsBase Object2)
		{
			// both are null
			if (Object1 == null && Object2 == null)
				return true;

			// one or the other is null, but not both
			if (Object1 == null ^ Object2 == null)
				return false;
				
			bool equal = true;
			if (Object1.EmployeeSkillId != Object2.EmployeeSkillId)
				equal = false;
			if ( Object1.EmployeeId != null && Object2.EmployeeId != null )
			{
				if (Object1.EmployeeId != Object2.EmployeeId)
					equal = false;
			}
			else if (Object1.EmployeeId == null ^ Object2.EmployeeId == null )
			{
				equal = false;
			}
			if ( Object1.SkillCode != null && Object2.SkillCode != null )
			{
				if (Object1.SkillCode != Object2.SkillCode)
					equal = false;
			}
			else if (Object1.SkillCode == null ^ Object2.SkillCode == null )
			{
				equal = false;
			}
			if ( Object1.SkillLevel != null && Object2.SkillLevel != null )
			{
				if (Object1.SkillLevel != Object2.SkillLevel)
					equal = false;
			}
			else if (Object1.SkillLevel == null ^ Object2.SkillLevel == null )
			{
				equal = false;
			}
			if ( Object1.CreatedOn != null && Object2.CreatedOn != null )
			{
				if (Object1.CreatedOn != Object2.CreatedOn)
					equal = false;
			}
			else if (Object1.CreatedOn == null ^ Object2.CreatedOn == null )
			{
				equal = false;
			}
					
			return equal;
		}
		
		#endregion
		
		#region IComparable Members
		///<summary>
		/// Compares this instance to a specified object and returns an indication of their relative values.
		///<param name="obj">An object to compare to this instance, or a null reference (Nothing in Visual Basic).</param>
		///</summary>
		///<returns>A signed integer that indicates the relative order of this instance and obj.</returns>
		public virtual int CompareTo(object obj)
		{
			throw new NotImplementedException();
			//return this. GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]) .CompareTo(((EmployeeSkillsBase)obj).GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]));
		}
		
		/*
		// static method to get a Comparer object
        public static EmployeeSkillsComparer GetComparer()
        {
            return new EmployeeSkillsComparer();
        }
        */

        // Comparer delegates back to EmployeeSkills
        // Employee uses the integer's default
        // CompareTo method
        /*
        public int CompareTo(Item rhs)
        {
            return this.Id.CompareTo(rhs.Id);
        }
        */

/*
        // Special implementation to be called by custom comparer
        public int CompareTo(EmployeeSkills rhs, EmployeeSkillsColumn which)
        {
            switch (which)
            {
            	
            	
            	case EmployeeSkillsColumn.EmployeeSkillId:
            		return this.EmployeeSkillId.CompareTo(rhs.EmployeeSkillId);
            		
            		                 
            	
            	
            	case EmployeeSkillsColumn.EmployeeId:
            		return this.EmployeeId.Value.CompareTo(rhs.EmployeeId.Value);
            		
            		                 
            	
            	
            	case EmployeeSkillsColumn.SkillCode:
            		return this.SkillCode.CompareTo(rhs.SkillCode);
            		
            		                 
            	
            	
            	case EmployeeSkillsColumn.SkillLevel:
            		return this.SkillLevel.CompareTo(rhs.SkillLevel);
            		
            		                 
            	
            	
            	case EmployeeSkillsColumn.CreatedOn:
            		return this.CreatedOn.Value.CompareTo(rhs.CreatedOn.Value);
            		
            		                 
            }
            return 0;
        }
        */
	
		#endregion
		
		#region IComponent Members
		
		private ISite _site = null;

		/// <summary>
		/// Gets or Sets the site where this data is located.
		/// </summary>
		[XmlIgnore]
		[SoapIgnore]
		[Browsable(false)]
		public ISite Site
		{
			get{ return this._site; }
			set{ this._site = value; }
		}

		#endregion

		#region IDisposable Members
		
		/// <summary>
		/// Notify those that care when we dispose.
		/// </summary>
		[field:NonSerialized]
		public event System.EventHandler Disposed;

		/// <summary>
		/// Clean up. Nothing here though.
		/// </summary>
		public virtual void Dispose()
		{
			this.parentCollection = null;
			this.Dispose(true);
			GC.SuppressFinalize(this);
		}
		
		/// <summary>
		/// Clean up.
		/// </summary>
		protected virtual void Dispose(bool disposing)
		{
			if (disposing)
			{
				EventHandler handler = Disposed;
				if (handler != null)
					handler(this, EventArgs.Empty);
			}
		}
		
		#endregion
				
		#region IEntityKey<EmployeeSkillsKey> Members
		
		// member variable for the EntityId property
		private EmployeeSkillsKey _entityId;

		/// <summary>
		/// Gets or sets the EntityId property.
		/// </summary>
		[XmlIgnore]
		public virtual EmployeeSkillsKey EntityId
		{
			get
			{
				if ( _entityId == null )
				{
					_entityId = new EmployeeSkillsKey(this);
				}

				return _entityId;
			}
			set
			{
				if ( value != null )
				{
					value.Entity = this;
				}
				
				_entityId = value;
			}
		}
		
		#endregion
		
		#region EntityState
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false) , XmlIgnoreAttribute()]
		public override EntityState EntityState 
		{ 
			get{ return entityData.EntityState;	 } 
			set{ entityData.EntityState = value; } 
		}
		#endregion 
		
		#region EntityTrackingKey
		///<summary>
		/// Provides the tracking key for the <see cref="EntityLocator"/>
		///</summary>
		[XmlIgnore]
		public override string EntityTrackingKey
		{
			get
			{
				if(entityTrackingKey == null)
					entityTrackingKey = new System.Text.StringBuilder("EmployeeSkills")
					.Append("|").Append( this.EmployeeSkillId.ToString()).ToString();
				return entityTrackingKey;
			}
			set
		    {
		        if (value != null)
                    entityTrackingKey = value;
		    }
		}
		#endregion 
		
		#region ToString Method
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return string.Format(System.Globalization.CultureInfo.InvariantCulture,
				"{6}{5}- EmployeeSkillId: {0}{5}- EmployeeId: {1}{5}- SkillCode: {2}{5}- SkillLevel: {3}{5}- CreatedOn: {4}{5}{7}", 
				this.EmployeeSkillId,
				(this.EmployeeId == null) ? string.Empty : this.EmployeeId.ToString(),
				(this.SkillCode == null) ? string.Empty : this.SkillCode.ToString(),
				(this.SkillLevel == null) ? string.Empty : this.SkillLevel.ToString(),
				(this.CreatedOn == null) ? string.Empty : this.CreatedOn.ToString(),
				System.Environment.NewLine, 
				this.GetType(),
				this.Error.Length == 0 ? string.Empty : string.Format("- Error: {0}\n",this.Error));
		}
		
		#endregion ToString Method
		
		#region Inner data class
		
	/// <summary>
	///		The data structure representation of the 'EmployeeSkills' table.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	[EditorBrowsable(EditorBrowsableState.Never)]
	[Serializable]
	internal protected class EmployeeSkillsEntityData : ICloneable, ICloneableEx
	{
		#region Variable Declarations
		private EntityState currentEntityState = EntityState.Added;
		
		#region Primary key(s)
		/// <summary>			
		/// EmployeeSkillId : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "EmployeeSkills"</remarks>
		public System.Int32 EmployeeSkillId;
			
		#endregion
		
		#region Non Primary key(s)
		
		/// <summary>
		/// EmployeeId : 
		/// </summary>
		public System.Int32? EmployeeId = null;
		
		/// <summary>
		/// SkillCode : 
		/// </summary>
		public System.String SkillCode = null;
		
		/// <summary>
		/// SkillLevel : 
		/// </summary>
		public System.String SkillLevel = null;
		
		/// <summary>
		/// CreatedOn : 
		/// </summary>
		public System.DateTime? CreatedOn = null;
		#endregion
			
		#region Source Foreign Key Property
				
		private Skill _skillCodeSource = null;
		
		/// <summary>
		/// Gets or sets the source <see cref="Skill"/>.
		/// </summary>
		/// <value>The source Skill for SkillCode.</value>
		[XmlIgnore()]
		[Browsable(false)]
		public virtual Skill SkillCodeSource
      	{
            get { return this._skillCodeSource; }
            set { this._skillCodeSource = value; }
      	}
		private SkillLevels _skillLevelSource = null;
		
		/// <summary>
		/// Gets or sets the source <see cref="SkillLevels"/>.
		/// </summary>
		/// <value>The source SkillLevels for SkillLevel.</value>
		[XmlIgnore()]
		[Browsable(false)]
		public virtual SkillLevels SkillLevelSource
      	{
            get { return this._skillLevelSource; }
            set { this._skillLevelSource = value; }
      	}
		private Employee _employeeIdSource = null;
		
		/// <summary>
		/// Gets or sets the source <see cref="Employee"/>.
		/// </summary>
		/// <value>The source Employee for EmployeeId.</value>
		[XmlIgnore()]
		[Browsable(false)]
		public virtual Employee EmployeeIdSource
      	{
            get { return this._employeeIdSource; }
            set { this._employeeIdSource = value; }
      	}
		#endregion
        
		#endregion Variable Declarations

		#region Data Properties

		#endregion Data Properties
		#region Clone Method

		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public Object Clone()
		{
			EmployeeSkillsEntityData _tmp = new EmployeeSkillsEntityData();
						
			_tmp.EmployeeSkillId = this.EmployeeSkillId;
			
			_tmp.EmployeeId = this.EmployeeId;
			_tmp.SkillCode = this.SkillCode;
			_tmp.SkillLevel = this.SkillLevel;
			_tmp.CreatedOn = this.CreatedOn;
			
			#region Source Parent Composite Entities
			if (this.SkillCodeSource != null)
				_tmp.SkillCodeSource = MakeCopyOf(this.SkillCodeSource) as Skill;
			if (this.SkillLevelSource != null)
				_tmp.SkillLevelSource = MakeCopyOf(this.SkillLevelSource) as SkillLevels;
			if (this.EmployeeIdSource != null)
				_tmp.EmployeeIdSource = MakeCopyOf(this.EmployeeIdSource) as Employee;
			#endregion
		
			#region Child Collections
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public object Clone(IDictionary existingCopies)
		{
			if (existingCopies == null)
				existingCopies = new Hashtable();
				
			EmployeeSkillsEntityData _tmp = new EmployeeSkillsEntityData();
						
			_tmp.EmployeeSkillId = this.EmployeeSkillId;
			
			_tmp.EmployeeId = this.EmployeeId;
			_tmp.SkillCode = this.SkillCode;
			_tmp.SkillLevel = this.SkillLevel;
			_tmp.CreatedOn = this.CreatedOn;
			
			#region Source Parent Composite Entities
			if (this.SkillCodeSource != null && existingCopies.Contains(this.SkillCodeSource))
				_tmp.SkillCodeSource = existingCopies[this.SkillCodeSource] as Skill;
			else
				_tmp.SkillCodeSource = MakeCopyOf(this.SkillCodeSource, existingCopies) as Skill;
			if (this.SkillLevelSource != null && existingCopies.Contains(this.SkillLevelSource))
				_tmp.SkillLevelSource = existingCopies[this.SkillLevelSource] as SkillLevels;
			else
				_tmp.SkillLevelSource = MakeCopyOf(this.SkillLevelSource, existingCopies) as SkillLevels;
			if (this.EmployeeIdSource != null && existingCopies.Contains(this.EmployeeIdSource))
				_tmp.EmployeeIdSource = existingCopies[this.EmployeeIdSource] as Employee;
			else
				_tmp.EmployeeIdSource = MakeCopyOf(this.EmployeeIdSource, existingCopies) as Employee;
			#endregion
		
			#region Child Collections
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		#endregion Clone Method
		
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public EntityState	EntityState
		{
			get { return currentEntityState;  }
			set { currentEntityState = value; }
		}
	
	}//End struct

		#endregion
		
				
		
		#region Events trigger
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="EmployeeSkillsColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanging(EmployeeSkillsColumn column)
		{
			OnColumnChanging(column, null);
			return;
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="EmployeeSkillsColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanged(EmployeeSkillsColumn column)
		{
			OnColumnChanged(column, null);
			return;
		} 
		
		
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="EmployeeSkillsColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanging(EmployeeSkillsColumn column, object value)
		{
			if(IsEntityTracked && EntityState != EntityState.Added && !EntityManager.TrackChangedEntities)
                EntityManager.StopTracking(entityTrackingKey);
                
			if (!SuppressEntityEvents)
			{
				EmployeeSkillsEventHandler handler = ColumnChanging;
				if(handler != null)
				{
					handler(this, new EmployeeSkillsEventArgs(column, value));
				}
			}
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="EmployeeSkillsColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanged(EmployeeSkillsColumn column, object value)
		{
			if (!SuppressEntityEvents)
			{
				EmployeeSkillsEventHandler handler = ColumnChanged;
				if(handler != null)
				{
					handler(this, new EmployeeSkillsEventArgs(column, value));
				}
			
				// warn the parent list that i have changed
				OnEntityChanged();
			}
		} 
		#endregion
			
	} // End Class
	
	
	#region EmployeeSkillsEventArgs class
	/// <summary>
	/// Provides data for the ColumnChanging and ColumnChanged events.
	/// </summary>
	/// <remarks>
	/// The ColumnChanging and ColumnChanged events occur when a change is made to the value 
	/// of a property of a <see cref="EmployeeSkills"/> object.
	/// </remarks>
	public class EmployeeSkillsEventArgs : System.EventArgs
	{
		private EmployeeSkillsColumn column;
		private object value;
		
		///<summary>
		/// Initalizes a new Instance of the EmployeeSkillsEventArgs class.
		///</summary>
		public EmployeeSkillsEventArgs(EmployeeSkillsColumn column)
		{
			this.column = column;
		}
		
		///<summary>
		/// Initalizes a new Instance of the EmployeeSkillsEventArgs class.
		///</summary>
		public EmployeeSkillsEventArgs(EmployeeSkillsColumn column, object value)
		{
			this.column = column;
			this.value = value;
		}
		
		///<summary>
		/// The EmployeeSkillsColumn that was modified, which has raised the event.
		///</summary>
		///<value cref="EmployeeSkillsColumn" />
		public EmployeeSkillsColumn Column { get { return this.column; } }
		
		/// <summary>
        /// Gets the current value of the column.
        /// </summary>
        /// <value>The current value of the column.</value>
		public object Value{ get { return this.value; } }

	}
	#endregion
	
	///<summary>
	/// Define a delegate for all EmployeeSkills related events.
	///</summary>
	public delegate void EmployeeSkillsEventHandler(object sender, EmployeeSkillsEventArgs e);
	
	#region EmployeeSkillsComparer
		
	/// <summary>
	///	Strongly Typed IComparer
	/// </summary>
	public class EmployeeSkillsComparer : System.Collections.Generic.IComparer<EmployeeSkills>
	{
		EmployeeSkillsColumn whichComparison;
		
		/// <summary>
        /// Initializes a new instance of the <see cref="T:EmployeeSkillsComparer"/> class.
        /// </summary>
		public EmployeeSkillsComparer()
        {            
        }               
        
        /// <summary>
        /// Initializes a new instance of the <see cref="T:EmployeeSkillsComparer"/> class.
        /// </summary>
        /// <param name="column">The column to sort on.</param>
        public EmployeeSkillsComparer(EmployeeSkillsColumn column)
        {
            this.whichComparison = column;
        }

		/// <summary>
        /// Determines whether the specified <see cref="EmployeeSkills"/> instances are considered equal.
        /// </summary>
        /// <param name="a">The first <see cref="EmployeeSkills"/> to compare.</param>
        /// <param name="b">The second <c>EmployeeSkills</c> to compare.</param>
        /// <returns>true if objA is the same instance as objB or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
        public bool Equals(EmployeeSkills a, EmployeeSkills b)
        {
            return this.Compare(a, b) == 0;
        }

		/// <summary>
        /// Gets the hash code of the specified entity.
        /// </summary>
        /// <param name="entity">The entity.</param>
        /// <returns></returns>
        public int GetHashCode(EmployeeSkills entity)
        {
            return entity.GetHashCode();
        }

        /// <summary>
        /// Performs a case-insensitive comparison of two objects of the same type and returns a value indicating whether one is less than, equal to, or greater than the other.
        /// </summary>
        /// <param name="a">The first object to compare.</param>
        /// <param name="b">The second object to compare.</param>
        /// <returns></returns>
        public int Compare(EmployeeSkills a, EmployeeSkills b)
        {
        	EntityPropertyComparer entityPropertyComparer = new EntityPropertyComparer(this.whichComparison.ToString());
        	return entityPropertyComparer.Compare(a, b);
        }

		/// <summary>
        /// Gets or sets the column that will be used for comparison.
        /// </summary>
        /// <value>The comparison column.</value>
        public EmployeeSkillsColumn WhichComparison
        {
            get { return this.whichComparison; }
            set { this.whichComparison = value; }
        }
	}
	
	#endregion
	
	#region EmployeeSkillsKey Class

	/// <summary>
	/// Wraps the unique identifier values for the <see cref="EmployeeSkills"/> object.
	/// </summary>
	[Serializable]
	[CLSCompliant(true)]
	public class EmployeeSkillsKey : EntityKeyBase
	{
		#region Constructors
		
		/// <summary>
		/// Initializes a new instance of the EmployeeSkillsKey class.
		/// </summary>
		public EmployeeSkillsKey()
		{
		}
		
		/// <summary>
		/// Initializes a new instance of the EmployeeSkillsKey class.
		/// </summary>
		public EmployeeSkillsKey(EmployeeSkillsBase entity)
		{
			this.Entity = entity;

			#region Init Properties

			if ( entity != null )
			{
				this.EmployeeSkillId = entity.EmployeeSkillId;
			}

			#endregion
		}
		
		/// <summary>
		/// Initializes a new instance of the EmployeeSkillsKey class.
		/// </summary>
		public EmployeeSkillsKey(System.Int32 _employeeSkillId)
		{
			#region Init Properties

			this.EmployeeSkillId = _employeeSkillId;

			#endregion
		}
		
		#endregion Constructors

		#region Properties
		
		// member variable for the Entity property
		private EmployeeSkillsBase _entity;
		
		/// <summary>
		/// Gets or sets the Entity property.
		/// </summary>
		public EmployeeSkillsBase Entity
		{
			get { return _entity; }
			set { _entity = value; }
		}
		
		// member variable for the EmployeeSkillId property
		private System.Int32 _employeeSkillId;
		
		/// <summary>
		/// Gets or sets the EmployeeSkillId property.
		/// </summary>
		public System.Int32 EmployeeSkillId
		{
			get { return _employeeSkillId; }
			set
			{
				if ( this.Entity != null )
					this.Entity.EmployeeSkillId = value;
				
				_employeeSkillId = value;
			}
		}
		
		#endregion

		#region Methods
		
		/// <summary>
		/// Reads values from the supplied <see cref="IDictionary"/> object into
		/// properties of the current object.
		/// </summary>
		/// <param name="values">An <see cref="IDictionary"/> instance that contains
		/// the key/value pairs to be used as property values.</param>
		public override void Load(IDictionary values)
		{
			#region Init Properties

			if ( values != null )
			{
				EmployeeSkillId = ( values["EmployeeSkillId"] != null ) ? (System.Int32) EntityUtil.ChangeType(values["EmployeeSkillId"], typeof(System.Int32)) : (int)0;
			}

			#endregion
		}

		/// <summary>
		/// Creates a new <see cref="IDictionary"/> object and populates it
		/// with the property values of the current object.
		/// </summary>
		/// <returns>A collection of name/value pairs.</returns>
		public override IDictionary ToDictionary()
		{
			IDictionary values = new Hashtable();

			#region Init Dictionary

			values.Add("EmployeeSkillId", EmployeeSkillId);

			#endregion Init Dictionary

			return values;
		}
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return String.Format("EmployeeSkillId: {0}{1}",
								EmployeeSkillId,
								System.Environment.NewLine);
		}

		#endregion Methods
	}
	
	#endregion	

	#region EmployeeSkillsColumn Enum
	
	/// <summary>
	/// Enumerate the EmployeeSkills columns.
	/// </summary>
	[Serializable]
	public enum EmployeeSkillsColumn : int
	{
		/// <summary>
		/// EmployeeSkillId : 
		/// </summary>
		[EnumTextValue("Employee Skill Id")]
		[ColumnEnum("EmployeeSkillId", typeof(System.Int32), System.Data.DbType.Int32, true, true, false)]
		EmployeeSkillId = 1,
		/// <summary>
		/// EmployeeId : 
		/// </summary>
		[EnumTextValue("Employee Id")]
		[ColumnEnum("EmployeeId", typeof(System.Int32), System.Data.DbType.Int32, false, false, true)]
		EmployeeId = 2,
		/// <summary>
		/// SkillCode : 
		/// </summary>
		[EnumTextValue("Skill Code")]
		[ColumnEnum("SkillCode", typeof(System.String), System.Data.DbType.AnsiString, false, false, true, 10)]
		SkillCode = 3,
		/// <summary>
		/// SkillLevel : 
		/// </summary>
		[EnumTextValue("Skill Level")]
		[ColumnEnum("SkillLevel", typeof(System.String), System.Data.DbType.AnsiString, false, false, true, 10)]
		SkillLevel = 4,
		/// <summary>
		/// CreatedOn : 
		/// </summary>
		[EnumTextValue("Created On")]
		[ColumnEnum("CreatedOn", typeof(System.DateTime), System.Data.DbType.DateTime, false, false, true)]
		CreatedOn = 5
	}//End enum

	#endregion EmployeeSkillsColumn Enum

} // end namespace
