using System;
using System.ComponentModel;

namespace EmployeeDB.BLL
{
	/// <summary>
	///		The data structure representation of the 'Address' table via interface.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	public interface IAddress 
	{
		/// <summary>			
		/// AddressId : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "Address"</remarks>
		System.Int32 AddressId { get; set; }
				
		
		
		/// <summary>
		/// EmployeeId : 
		/// </summary>
		System.Int32  EmployeeId  { get; set; }
		
		/// <summary>
		/// Line1 : 
		/// </summary>
		System.String  Line1  { get; set; }
		
		/// <summary>
		/// Line2 : 
		/// </summary>
		System.String  Line2  { get; set; }
		
		/// <summary>
		/// TownCity : 
		/// </summary>
		System.String  TownCity  { get; set; }
		
		/// <summary>
		/// StateOrProvince : 
		/// </summary>
		System.String  StateOrProvince  { get; set; }
		
		/// <summary>
		/// PostCod : 
		/// </summary>
		System.String  PostCod  { get; set; }
		
		/// <summary>
		/// CountryCode : 
		/// </summary>
		System.String  CountryCode  { get; set; }
			
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		System.Object Clone();
		
		#region Data Properties

		#endregion Data Properties

	}
}


