using System;
using System.ComponentModel;

namespace EmployeeDB.BLL
{
	/// <summary>
	///		The data structure representation of the 'EmployeeSkills' table via interface.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	public interface IEmployeeSkills 
	{
		/// <summary>			
		/// EmployeeSkillId : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "EmployeeSkills"</remarks>
		System.Int32 EmployeeSkillId { get; set; }
				
		
		
		/// <summary>
		/// EmployeeId : 
		/// </summary>
		System.Int32?  EmployeeId  { get; set; }
		
		/// <summary>
		/// SkillCode : 
		/// </summary>
		System.String  SkillCode  { get; set; }
		
		/// <summary>
		/// SkillLevel : 
		/// </summary>
		System.String  SkillLevel  { get; set; }
		
		/// <summary>
		/// CreatedOn : 
		/// </summary>
		System.DateTime?  CreatedOn  { get; set; }
			
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		System.Object Clone();
		
		#region Data Properties

		#endregion Data Properties

	}
}


