using System;
using System.ComponentModel;

namespace EmployeeDB.BLL
{
	/// <summary>
	///		The data structure representation of the 'Employee' table via interface.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	public interface IEmployee 
	{
		/// <summary>			
		/// EmployeeId : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "Employee"</remarks>
		System.Int32 EmployeeId { get; set; }
				
		
		
		/// <summary>
		/// EmployeeCode : 
		/// </summary>
		System.String  EmployeeCode  { get; set; }
		
		/// <summary>
		/// FullName : 
		/// </summary>
		System.String  FullName  { get; set; }
		
		/// <summary>
		/// FirstName : 
		/// </summary>
		System.String  FirstName  { get; set; }
		
		/// <summary>
		/// MiddlesName : 
		/// </summary>
		System.String  MiddlesName  { get; set; }
		
		/// <summary>
		/// LastName : 
		/// </summary>
		System.String  LastName  { get; set; }
		
		/// <summary>
		/// DOB : 
		/// </summary>
		System.DateTime?  DOB  { get; set; }
		
		/// <summary>
		/// Email : 
		/// </summary>
		System.String  Email  { get; set; }
		
		/// <summary>
		/// Bio : 
		/// </summary>
		System.String  Bio  { get; set; }
		
		/// <summary>
		/// CreatedOn : 
		/// </summary>
		System.DateTime?  CreatedOn  { get; set; }
			
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		System.Object Clone();
		
		#region Data Properties


		/// <summary>
		///	Holds a collection of entity objects
		///	which are related to this object through the relation _employeeSkillsEmployeeId
		/// </summary>	
		TList<EmployeeSkills> EmployeeSkillsCollection {  get;  set;}	


		/// <summary>
		///	Holds a collection of entity objects
		///	which are related to this object through the relation _employeeDepartmentsEmployeeId
		/// </summary>	
		TList<EmployeeDepartments> EmployeeDepartmentsCollection {  get;  set;}	


		/// <summary>
		///	Holds a collection of entity objects
		///	which are related to this object through the relation _employeeSalaryEmployeeId
		/// </summary>	
		TList<EmployeeSalary> EmployeeSalaryCollection {  get;  set;}	


		/// <summary>
		///	Holds a collection of entity objects
		///	which are related to this object through the relation _addressEmployeeId
		/// </summary>	
		TList<Address> AddressCollection {  get;  set;}	


		/// <summary>
		///	Holds a collection of entity objects
		///	which are related to this object through the relation _bankAccountsEmployeeId
		/// </summary>	
		TList<BankAccounts> BankAccountsCollection {  get;  set;}	

		#endregion Data Properties

	}
}


