using System;
using System.ComponentModel;

namespace EmployeeDB.BLL
{
	/// <summary>
	///		The data structure representation of the 'EmployeeDepartments' table via interface.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	public interface IEmployeeDepartments 
	{
		/// <summary>			
		/// EmployeeDepartmentId : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "EmployeeDepartments"</remarks>
		System.Int32 EmployeeDepartmentId { get; set; }
				
		
		
		/// <summary>
		/// DepartmentCode : 
		/// </summary>
		System.String  DepartmentCode  { get; set; }
		
		/// <summary>
		/// EmployeeId : 
		/// </summary>
		System.Int32?  EmployeeId  { get; set; }
		
		/// <summary>
		/// CreatedOn : 
		/// </summary>
		System.DateTime?  CreatedOn  { get; set; }
			
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		System.Object Clone();
		
		#region Data Properties

		#endregion Data Properties

	}
}


