using System;
using System.ComponentModel;

namespace EmployeeDB.BLL
{
	/// <summary>
	///		The data structure representation of the 'EmployeeSalary' table via interface.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	public interface IEmployeeSalary 
	{
		/// <summary>			
		/// EmployeeSalaryId : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "EmployeeSalary"</remarks>
		System.Int32 EmployeeSalaryId { get; set; }
				
		
		
		/// <summary>
		/// EmployeeId : 
		/// </summary>
		System.Int32?  EmployeeId  { get; set; }
		
		/// <summary>
		/// SalaryAmount : 
		/// </summary>
		System.Decimal?  SalaryAmount  { get; set; }
		
		/// <summary>
		/// ApprovedOn : 
		/// </summary>
		System.DateTime?  ApprovedOn  { get; set; }
		
		/// <summary>
		/// ApprovedBy : 
		/// </summary>
		System.String  ApprovedBy  { get; set; }
		
		/// <summary>
		/// IsActive : 
		/// </summary>
		System.Boolean?  IsActive  { get; set; }
			
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		System.Object Clone();
		
		#region Data Properties

		#endregion Data Properties

	}
}


